"""Cinematic presentation layer for the live CARAPACE assurance lab."""

FUTURE_CSS = r"""
:root{--ink:#f5f8ff;--muted:#90a5c6;--line:rgba(113,183,250,.28);--cyan:#43eaff;--blue:#75a4ff;--mint:#44f3c7;--red:#ff536d;--deep:#020814}
*{box-sizing:border-box}html{background:var(--deep);color-scheme:dark}body{background:#020814;color:var(--ink);overflow-x:hidden}
body:before{content:"";position:fixed;inset:0;z-index:-3;background:radial-gradient(circle at 45% 38%,rgba(23,88,151,.32),transparent 39%),linear-gradient(#031020,#020814 70%)}
body:after{content:"";position:fixed;inset:45% -25% -30%;z-index:-2;background-image:linear-gradient(rgba(66,148,215,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(66,148,215,.14) 1px,transparent 1px);background-size:70px 70px;transform:perspective(520px) rotateX(64deg);transform-origin:50% 100%;pointer-events:none}
.topbar{position:sticky;top:0;z-index:50;background:rgba(2,10,21,.9);border-bottom:1px solid rgba(107,180,255,.22);backdrop-filter:blur(24px)}
.topbar-inner{width:min(1560px,calc(100% - 32px));min-height:76px;margin:auto;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:18px}.brand{display:flex;align-items:center;gap:11px;font-weight:950;letter-spacing:.13em;white-space:nowrap}.brand i{font-size:31px;color:var(--cyan);filter:drop-shadow(0 0 12px #34cfea)}.brand span{color:#58a7ff}.brand small{font-size:13px;letter-spacing:0;color:#dce8f8;font-weight:700;padding-left:20px;border-left:1px solid rgba(126,173,232,.32)}
.toplinks{justify-self:center;display:flex;align-items:center;padding:4px;border:1px solid rgba(96,154,230,.3);border-radius:999px;background:rgba(8,26,48,.76);overflow:hidden}.toplinks a{display:flex;gap:7px;align-items:center;text-decoration:none;color:#9fb3d4;border:0;border-radius:999px;padding:10px 17px;font-size:11px;font-weight:750;white-space:nowrap}.toplinks a:first-child{color:#fff;background:linear-gradient(rgba(71,126,226,.5),rgba(32,65,125,.6));box-shadow:inset 0 0 0 1px rgba(117,181,255,.56),0 0 22px rgba(74,122,255,.3)}
.system-strip{display:flex;align-items:center;gap:14px;white-space:nowrap}.system-live{display:grid;grid-template-columns:auto auto;gap:0 8px;align-items:center}.system-live .pulse{grid-row:1/3;width:9px;height:9px;border-radius:50%;background:var(--mint);box-shadow:0 0 16px var(--mint)}.system-live b{font-size:10px;letter-spacing:.1em;color:#aff1ee}.system-live small{font-size:8px;color:#7790b5}.system-avatar{width:38px;height:38px;display:grid;place-items:center;border:1px solid rgba(107,177,255,.4);border-radius:50%;font-size:10px;background:#09182b}
main{width:min(1560px,calc(100% - 32px));padding:18px 0 70px;margin:auto}.hero,.statusbar{display:none}.panel,.status,.pipe div{background:rgba(6,18,33,.82);border-color:var(--line)}.section-head{scroll-margin-top:92px}.section-head h2{color:#f5f8ff}.section-head p,.lead,.bank-guide p,.bank-guide li,.table-toolbar p,.experiment-main>p,.proofops>p,.lens-result>p{color:var(--muted)}.eyebrow{color:var(--cyan)}.bank-guide,.lens-form,.source-grid{background:rgba(8,23,41,.72);border-color:var(--line)}.credential,.lens-form textarea,.lens-form input,.receipt-stage,.proof-card,.result-card,.secondary{background:rgba(4,14,27,.76);border-color:var(--line);color:var(--ink)}.bank-frame-wrap{background:#fff}.windowbar{background:#0a1728;border-color:var(--line);color:var(--muted)}th{background:#08172a;color:#8297b7}td,th{border-color:rgba(137,171,217,.13)}.table-scroll,.mapping,.promise-row{border-color:var(--line)}.promise{background:#071526}.step,.lens-fact{background:rgba(83,125,183,.1)}.proofops,.receipt{background:rgba(6,24,41,.78);border-color:rgba(97,175,235,.31)}.mapping h4{background:rgba(8,23,41,.9);border-color:var(--line)}.honesty{background:rgba(255,196,75,.08);border-color:rgba(255,196,75,.28);color:#f0dca6}.primary,.open-bank{background:linear-gradient(110deg,#2d68d4,#4f8fff);color:#fff;box-shadow:0 12px 34px rgba(47,112,220,.3)}
.future-shell{position:relative;min-height:846px;border:1px solid rgba(89,164,241,.4);border-radius:26px;overflow:hidden;background:linear-gradient(180deg,rgba(3,15,30,.58),rgba(2,9,19,.93));box-shadow:0 42px 120px rgba(0,0,0,.54),inset 0 1px rgba(197,226,255,.08);isolation:isolate}.future-shell:before{content:"";position:absolute;inset:0;z-index:-2;background:radial-gradient(ellipse at 40% 47%,rgba(33,119,205,.3),transparent 43%),repeating-linear-gradient(90deg,transparent 0 104px,rgba(83,154,220,.05) 105px 106px)}
#assurance-canvas{position:absolute;inset:145px 310px 100px 0;width:calc(100% - 310px);height:calc(100% - 245px);z-index:2;pointer-events:none}.future-grid{position:relative;z-index:3;display:grid;grid-template-columns:minmax(0,1fr) 330px;min-height:740px}.future-main{min-width:0;padding:28px 23px 105px}.future-aside{border-left:1px solid rgba(109,178,244,.34);background:linear-gradient(rgba(6,20,38,.86),rgba(4,14,29,.94));padding:20px 16px;backdrop-filter:blur(22px)}
.future-intro{height:148px;display:grid;grid-template-columns:minmax(430px,1fr) 245px;gap:22px;padding:0 7px}.future-intro h1{font-size:clamp(38px,4vw,61px);line-height:.96;letter-spacing:-.052em;margin:3px 0 11px;color:#f7f9ff}.future-intro h1 span{color:#83a9ff}.future-intro p{margin:0;color:#a8bad6;font-size:15px;line-height:1.4}.promise-line{margin-top:16px;padding-left:22px;border-left:1px solid rgba(107,187,255,.6)}.promise-line b{display:block;color:#a9beff;font-size:9px;line-height:1.8;letter-spacing:.32em}.promise-line span{display:block;color:#9fb0cd;font-size:11px;line-height:1.45;margin-top:6px}.live-pill{display:none}
.assurance-world{position:relative;height:468px;perspective:1450px;transform-style:preserve-3d}.assurance-floor{position:absolute;inset:44% -2% -20%;z-index:-1;background-image:linear-gradient(rgba(69,162,237,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(69,162,237,.16) 1px,transparent 1px);background-size:62px 62px;transform:perspective(390px) rotateX(61deg);transform-origin:center bottom;mask-image:linear-gradient(transparent,#000 34%,transparent)}
.transaction-card,.outcome-card,.duplicate-card{position:absolute;border:1px solid rgba(115,194,255,.56);border-radius:11px;background:linear-gradient(135deg,rgba(20,60,98,.73),rgba(7,25,47,.7));box-shadow:inset 0 1px rgba(255,255,255,.17),0 0 28px rgba(60,168,255,.16);backdrop-filter:blur(13px)}.transaction-card{left:-2px;bottom:60px;width:146px;min-height:222px;padding:16px 14px;transform:rotateY(9deg)}.transaction-card .amount{font-size:22px;font-weight:900}.transaction-card .type{font-size:10px;color:#a7bad5;margin:2px 0 13px}.fact{margin:8px 0}.fact small{display:block;font-size:8px;color:#7792b8}.fact span{font-size:9px;color:#dce8fa}.token-id{font-family:ui-monospace,monospace}
.payment-core{position:absolute;left:127px;top:207px;width:76px;height:76px;border-radius:28px;border:2px solid #80eaff;background:radial-gradient(circle at 35% 25%,#92f8ff,#138bd1 46%,#10346e 78%);display:grid;place-items:center;font-size:30px;font-weight:900;box-shadow:0 0 0 10px rgba(63,192,255,.11),0 0 36px #27cfff,0 0 85px rgba(54,177,255,.56);transform:rotateY(20deg);z-index:6}.payment-core:after{content:"";position:absolute;right:-20px;width:24px;height:58px;border:1px solid #6ce7ff;border-radius:8px;background:linear-gradient(90deg,rgba(46,155,218,.12),rgba(91,233,255,.44));box-shadow:0 0 16px rgba(66,216,255,.5)}
.flow-panels{position:absolute;left:80px;right:108px;top:30px;bottom:25px;display:grid;grid-template-columns:repeat(5,1fr);gap:23px;align-items:center}.flow-node{position:relative;height:330px;border:1px solid rgba(105,183,255,.7);border-radius:7px;padding:25px 13px 17px;background:linear-gradient(140deg,rgba(30,76,119,.38),rgba(7,28,52,.55));box-shadow:inset 2px 0 rgba(179,224,255,.14),inset -2px 0 rgba(55,130,206,.19),0 24px 55px rgba(0,0,0,.31),0 0 24px rgba(52,147,230,.1);backdrop-filter:blur(7px);transform:rotateY(-3deg);transition:.5s ease;overflow:hidden}.flow-node:nth-child(even){transform:rotateY(3deg) translateY(-5px)}.flow-node:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(255,255,255,.06),transparent 14% 84%,rgba(89,188,255,.09))}.flow-node:hover{transform:translateY(-9px);border-color:#8de8ff;box-shadow:0 0 38px rgba(46,186,255,.23)}.node-icon{width:40px;height:40px;margin:0 auto 16px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(113,190,255,.7);font-size:21px;color:#c6e8ff;background:rgba(33,83,139,.4);box-shadow:0 0 20px rgba(74,161,255,.22)}.node-kicker{display:block;text-align:center;color:#eef6ff;font-weight:900;font-size:9px;white-space:nowrap}.node-sub{display:block;text-align:center;color:#9fb2d0;font-size:8px;margin-top:6px}.node-checks{position:absolute;left:13px;right:8px;bottom:17px;display:grid;gap:8px}.node-checks span{display:flex;align-items:center;gap:6px;color:#adc2db;font-size:7.5px}.node-checks i{font-size:12px;color:var(--mint);filter:drop-shadow(0 0 5px rgba(66,244,197,.7))}.flow-node[data-stage="4"]{border-color:rgba(255,91,114,.67);box-shadow:0 0 26px rgba(255,57,87,.15)}.flow-node[data-stage="5"] .node-icon{color:#8dffe3;border-color:#54f3d2;box-shadow:0 0 28px rgba(66,244,197,.34)}
.duplicate-card{left:57%;top:269px;width:178px;padding:11px 12px;z-index:7;border-color:rgba(255,86,108,.57);background:rgba(51,16,31,.86);box-shadow:0 0 29px rgba(255,59,88,.24);opacity:0;transform:translateY(10px);transition:.5s}.duplicate-card b{display:block;color:#ff8495;font-size:11px;margin-bottom:6px}.debit-row{display:grid;grid-template-columns:12px 1fr auto;gap:5px;font-size:7.5px;padding:5px 0;border-top:1px solid rgba(255,138,153,.18)}.debit-row em{font-style:normal;color:var(--mint)}.debit-row.bad em{color:#ff778b}.future-shell[data-phase="incident"] .duplicate-card,.future-shell[data-phase="resolved"] .duplicate-card{opacity:1;transform:none}.fault-pin{position:absolute;left:63%;top:181px;z-index:8;width:34px;height:34px;border:2px solid #fff;border-radius:50%;display:grid;place-items:center;color:#fff;background:var(--red);font-weight:900;box-shadow:0 0 0 5px rgba(255,62,91,.12),0 0 26px #ff405e;opacity:0;transition:.4s}.fault-pin.lower{top:253px}.future-shell[data-phase="incident"] .fault-pin,.future-shell[data-phase="resolved"] .fault-pin{opacity:1}
.outcome-card{right:-4px;bottom:84px;width:130px;min-height:166px;padding:16px 12px;text-align:center;transform:rotateY(-8deg);z-index:5}.shield-orb{width:50px;height:50px;border-radius:50%;margin:-43px auto 18px;display:grid;place-items:center;color:#eafff8;border:2px solid #63f3d1;background:rgba(20,121,121,.83);box-shadow:0 0 0 9px rgba(53,241,205,.1),0 0 30px rgba(53,241,205,.55);font-size:24px}.outcome-card b{display:block;font-size:9px}.outcome-card strong{display:block;font-size:18px;margin-top:47px}.outcome-card small{font-size:8px;color:#9bb0ca}
.future-actions{position:absolute;left:12px;bottom:10px;z-index:12;display:flex;align-items:center;gap:11px}.future-actions .primary{font-size:10px;padding:9px 14px}.future-actions small{font-size:8px;color:#7089ad}.motion-toggle{display:flex;align-items:center;gap:6px;color:#7890b2;font-size:8px}.switch{width:34px;height:19px;border-radius:999px;border:1px solid var(--line);background:#11243b;padding:2px}.switch:after{content:"";display:block;width:13px;height:13px;border-radius:50%;background:#dce9f8;transition:.2s}.switch[aria-checked="true"]:after{transform:translateX(15px);background:var(--cyan)}
.aside-head{display:flex;align-items:center;gap:9px;padding:0 5px 16px;border-bottom:1px solid rgba(112,173,231,.2);margin-bottom:17px}.aside-head i{font-size:24px;color:#82a7ff;filter:drop-shadow(0 0 11px #6f79ff)}.aside-head h2{font-size:16px;margin:0}.aside-head span{margin-left:auto;font-size:8px;letter-spacing:.13em;color:#8297b8}.plain-story{padding:2px 7px 13px}.plain-story p{font-size:16px;line-height:1.42;margin:0 0 8px;color:#edf3ff;font-weight:800}.evidence-block{position:relative;border:1px solid rgba(99,161,222,.36);border-radius:10px;padding:13px 13px 13px 48px;margin-top:10px;background:linear-gradient(110deg,rgba(12,41,70,.7),rgba(5,21,40,.74));min-height:63px}.evidence-block>i{position:absolute;left:14px;top:16px;font-size:21px;color:#78a6ff}.evidence-block small{display:block;color:#a5bad7;margin-bottom:4px;font-size:10px}.evidence-block strong{display:block;color:#e8f0ff;font-size:9px;line-height:1.4}.evidence-block.danger{border-color:rgba(255,87,108,.45);background:linear-gradient(110deg,rgba(70,19,34,.8),rgba(33,13,29,.72))}.evidence-block.danger>*{color:#ff8fa0}.good-evidence>i{color:var(--mint)}
.future-timeline{position:absolute;z-index:9;left:0;right:0;bottom:0;min-height:104px;border-top:1px solid rgba(93,166,235,.4);background:rgba(4,17,33,.95);backdrop-filter:blur(24px);display:grid;grid-template-columns:200px 1fr 186px;align-items:center;gap:13px;padding:12px 19px}.timeline-title{display:grid;grid-template-columns:42px 1fr;gap:9px;align-items:center;border-right:1px solid rgba(112,168,226,.22);min-height:64px}.timeline-title i{width:38px;height:38px;display:grid;place-items:center;border:1px solid rgba(77,170,255,.48);border-radius:50%;color:var(--cyan);font-size:19px}.timeline-title strong{display:block;font-size:11px}.timeline-title small{color:#7891b6;font-size:8px}.timeline-steps{display:grid;grid-template-columns:repeat(6,1fr);position:relative}.timeline-steps:before{content:"";position:absolute;left:8%;right:8%;top:11px;height:2px;background:linear-gradient(90deg,var(--cyan) 0 52%,var(--red) 52% 68%,var(--mint) 68% 84%,#334965 84%)}.timeline-step{text-align:center;color:#83a0c4;font-size:7px;position:relative;padding-top:30px}.timeline-step:before{content:"";position:absolute;top:3px;left:50%;width:16px;height:16px;border-radius:50%;transform:translateX(-50%);background:#162a43;border:2px solid #506d91}.timeline-step.done{color:#b7f9ea}.timeline-step.done:before{background:#0f8e83;border-color:#62ffe2;box-shadow:0 0 13px rgba(69,230,187,.72)}.timeline-step.fail{color:#ff8b9d}.timeline-step.fail:before{background:#d63350;border-color:#fff;box-shadow:0 0 15px #ff4561}.timeline-step b{display:block;font-size:7px;margin-bottom:3px}.timeline-step time{color:#647f9f}.review-link{text-align:center;border:1px solid rgba(105,158,255,.7);border-radius:11px;padding:12px;color:#e9efff;text-decoration:none;font-size:10px;font-weight:850;background:linear-gradient(110deg,rgba(53,82,188,.5),rgba(34,102,173,.38));box-shadow:0 0 25px rgba(68,115,255,.25)}.lab-divider{display:flex;align-items:center;gap:16px;margin:38px 0 0;color:#6f87a9;font-size:10px;letter-spacing:.18em;text-transform:uppercase}.lab-divider:before,.lab-divider:after{content:"";height:1px;background:var(--line);flex:1}
@media(max-width:1250px){.system-strip{display:none}.topbar-inner{grid-template-columns:auto 1fr}.future-grid{grid-template-columns:minmax(0,1fr) 285px}#assurance-canvas{right:285px;width:calc(100% - 285px)}.future-intro{grid-template-columns:1fr 190px}.flow-panels{gap:12px;left:70px;right:83px}.flow-node{padding-left:7px;padding-right:7px}.node-kicker{font-size:7.5px}.transaction-card{width:122px}.outcome-card{width:108px}.duplicate-card{left:54%;width:160px}}
@media(max-width:960px){main{width:100%;padding-top:0}.future-shell{border-radius:0;border-left:0;border-right:0}.future-grid{grid-template-columns:minmax(0,1fr) 245px}.future-main{padding-left:10px;padding-right:10px}.future-intro{height:135px;grid-template-columns:1fr}.future-intro h1{font-size:38px}.promise-line{display:none}.flow-panels{left:55px;right:58px;gap:7px}.flow-node{height:305px;padding:19px 4px 11px}.node-icon{width:31px;height:31px;font-size:16px}.node-sub{font-size:6px}.node-checks{left:5px}.node-checks span{font-size:6px}.transaction-card{width:100px;padding:11px 7px}.payment-core{left:84px;width:61px;height:61px}.outcome-card{width:86px}.duplicate-card{left:51%;width:140px}.future-aside{padding:14px 9px}.plain-story p{font-size:12px}.future-timeline{grid-template-columns:145px 1fr 140px;padding:10px}.timeline-title i{display:none}.timeline-title{grid-template-columns:1fr}.brand small{display:none}.toplinks a{padding:9px 10px}}
@media(max-width:760px){.topbar-inner{display:flex}.toplinks{margin-left:auto}.toplinks a:not(:first-child){display:none}.future-grid{grid-template-columns:1fr}.future-aside{border-left:0;border-top:1px solid var(--line);margin-bottom:104px}.assurance-world{overflow-x:auto}.assurance-world>*{min-width:700px}.future-timeline{position:fixed;grid-template-columns:1fr 115px}.timeline-title{display:none}.timeline-steps{grid-template-columns:repeat(6,80px);overflow-x:auto}.future-intro h1{font-size:34px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition-duration:.01ms!important}}
"""

ASSURANCE_FLOW_HTML = r"""
<section id="assurance" class="future-shell" data-phase="idle" aria-labelledby="assurance-title"><canvas id="assurance-canvas" aria-hidden="true"></canvas><div class="future-grid"><div class="future-main">
<div class="future-intro"><div><h1 id="assurance-title">See every payment.<br>Stop what’s <span>wrong.</span></h1><p>AI-powered assurance across the payment lifecycle.<br>Detect. Explain. Repair. Before it becomes loss.</p></div><div class="promise-line"><b>SAME PAYMENTS.<br>STRONGER BANKS.</b><span>From intent to resolution —<br>with AI on your side.</span></div><div id="ai-live-pill" class="live-pill"></div></div>
<div class="assurance-world"><div class="assurance-floor"></div><article class="transaction-card"><div class="amount">$49.99</div><div class="type">Payment token</div><div class="fact"><small>Customer</small><span>Demo customer</span></div><div class="fact"><small>Environment</small><span>Artificial money</span></div><div class="fact"><small>Payment method</small><span>Bank transfer</span></div><div class="fact"><small>Token ID</small><span class="token-id">pay_live_evidence</span></div></article><div id="payment-token" class="payment-core">$</div>
<div class="flow-panels">
<article class="flow-node" data-stage="1"><div class="node-icon"><i class="ph ph-user-circle"></i></div><b class="node-kicker">1. INTENT CHECKED</b><span class="node-sub">Customer request</span><div class="node-checks"><span><i class="ph-fill ph-check-circle"></i>Amount verified</span><span><i class="ph-fill ph-check-circle"></i>Risk checks clear</span><span><i class="ph-fill ph-check-circle"></i>Policy compliant</span></div></article>
<article class="flow-node" data-stage="2"><div class="node-icon"><i class="ph ph-credit-card"></i></div><b class="node-kicker">2. PAYMENT BOUND</b><span class="node-sub">Rules &amp; controls</span><div class="node-checks"><span><i class="ph-fill ph-check-circle"></i>Recipient bound</span><span><i class="ph-fill ph-check-circle"></i>Amount locked</span><span><i class="ph-fill ph-check-circle"></i>Nonce protected</span></div></article>
<article class="flow-node" data-stage="3"><div class="node-icon"><i class="ph ph-bank"></i></div><b class="node-kicker">3. BANK AUTHORISED</b><span class="node-sub">Bank processing</span><div class="node-checks"><span><i class="ph-fill ph-check-circle"></i>Authorisation OK</span><span><i class="ph-fill ph-check-circle"></i>Bank reference</span><span><i class="ph-fill ph-check-circle"></i>Funds captured</span></div></article>
<article class="flow-node" data-stage="4"><div class="node-icon"><i class="ph ph-receipt"></i></div><b class="node-kicker">4. LEDGER WITNESSED</b><span class="node-sub">Core bank record</span></article>
<article class="flow-node" data-stage="5"><div class="node-icon"><i class="ph ph-shield-check"></i></div><b class="node-kicker">5. REPAIR VERIFIED</b><span class="node-sub">Verify &amp; repair</span><div class="node-checks"><span><i class="ph-fill ph-check-circle"></i>Retry fault reproduced</span><span><i class="ph-fill ph-check-circle"></i>Duplicate prevented</span><span><i class="ph-fill ph-check-circle"></i>Ledger reconciled</span></div></article></div>
<div class="fault-pin">!</div><div class="fault-pin lower">!</div><div class="duplicate-card"><b>2 debits / 1 approved</b><div class="debit-row"><span>1</span><span>$49.99</span><em>Approved</em></div><div class="debit-row bad"><span>2</span><span>$49.99</span><em>Duplicate</em></div></div><article class="outcome-card"><div class="shield-orb"><i class="ph ph-shield-check"></i></div><b>Single valid debit</b><strong>$49.99</strong><small>Merchant settled</small></article></div>
<div class="future-actions"><button id="hero-run" class="primary" type="button">Run live assurance story</button><small id="hero-run-note">Official Bank of Anthos · artificial money</small><label class="motion-toggle"><button id="motion-switch" class="switch" type="button" role="switch" aria-checked="true"></button> Motion</label></div></div>
<aside class="future-aside"><div class="aside-head"><i class="ph-fill ph-sparkle"></i><h2>What happened</h2><span id="story-state">READY</span></div><div class="plain-story"><p id="story-line-1">You will approve one artificial $49.99 payment.</p><p id="story-line-2">CARAPACE will inspect the bank’s exact ledger evidence.</p><p id="story-line-3">Then it will reproduce and repair a controlled retry fault.</p></div><div id="incident-evidence" class="evidence-block"><i class="ph ph-warning-circle"></i><small>Assurance status</small><strong id="incident-status">Ready for a live evidence run</strong></div><div class="evidence-block"><i class="ph-fill ph-sparkle"></i><small>AI provenance</small><strong id="ai-provenance">Provider status loading…</strong></div><div class="evidence-block"><i class="ph ph-scroll"></i><small>Deterministic contract</small><strong id="contract-status">Financial verifier controls PASS / FAIL</strong></div><div class="evidence-block good-evidence"><i class="ph ph-package"></i><small>Evidence package</small><strong>Ledger rows · bank response · AI reasoning · test result</strong></div></aside></div>
<div class="future-timeline"><div class="timeline-title"><i class="ph ph-wave-sine"></i><div><strong>Assurance timeline</strong><small>From anomaly to resolution</small></div></div><div class="timeline-steps"><div class="timeline-step" data-time-stage="1"><b>Intent checked</b><time>Context</time></div><div class="timeline-step" data-time-stage="2"><b>Payment bound</b><time>Contract</time></div><div class="timeline-step" data-time-stage="3"><b>Bank authorised</b><time>Posting</time></div><div class="timeline-step" data-time-stage="4"><b>Mismatch detected</b><time>Evidence</time></div><div class="timeline-step" data-time-stage="5"><b>Repair verified</b><time>ProofOps</time></div><div class="timeline-step"><b>Human approval</b><time>Required</time></div></div><a class="review-link" href="#verification"><i class="ph ph-file-text"></i> Review evidence</a></div></section><div class="lab-divider">Explore every evidence surface</div>
"""

FUTURE_JS = r"""
<script type="module">
const shell=document.getElementById('assurance'),heroRun=document.getElementById('hero-run'),originalRun=document.getElementById('run'),note=document.getElementById('hero-run-note'),storyState=document.getElementById('story-state'),incident=document.getElementById('incident-evidence'),motionSwitch=document.getElementById('motion-switch'),nodes=[...document.querySelectorAll('.flow-node')],timeSteps=[...document.querySelectorAll('.timeline-step')];let ambient=true,stageTimer=null;
function setStage(stage,phase='running'){shell.dataset.phase=phase;nodes.forEach((n,i)=>{n.classList.toggle('done',i+1<stage);n.classList.toggle('active',i+1===stage&&phase!=='incident');n.classList.toggle('incident',i+1===4&&phase==='incident')});timeSteps.forEach((n,i)=>{n.classList.toggle('done',i+1<stage||(i+1===stage&&phase==='resolved'));n.classList.toggle('fail',i+1===4&&phase==='incident')})}
function resetStory(){clearInterval(stageTimer);setStage(1);storyState.textContent='RUNNING';heroRun.disabled=true;heroRun.textContent='Watching live evidence…';note.textContent='Promise → bank posting → ledger witness → ProofOps';document.getElementById('story-line-1').textContent='You approved one artificial $49.99 payment.';document.getElementById('story-line-2').textContent='CARAPACE is following its evidence into the bank ledger.';document.getElementById('story-line-3').textContent='No result is declared until the deterministic verifier checks it.';incident.classList.remove('danger');document.getElementById('incident-status').textContent='Live experiment running';document.getElementById('contract-status').textContent='Waiting for ledger evidence';let s=1;stageTimer=setInterval(()=>{if(s<3)setStage(++s)},1200)}
heroRun.addEventListener('click',()=>{resetStory();originalRun.click()});document.getElementById('results').scrollIntoView=()=>{};
new MutationObserver(()=>{if(!document.getElementById('results').classList.contains('visible'))return;clearInterval(stageTimer);setStage(4,'incident');storyState.textContent='MISMATCH';incident.classList.add('danger');document.getElementById('story-line-1').textContent='You approved one artificial $49.99 payment.';document.getElementById('story-line-2').textContent='The bank recorded two matching debit rows.';document.getElementById('story-line-3').textContent='CARAPACE reproduced the retry fault.';document.getElementById('incident-status').textContent='Critical mismatch contained · no real financial impact';document.getElementById('contract-status').textContent='Contract F1 failed · retry without idempotency'}).observe(document.getElementById('results'),{attributes:true});
new MutationObserver(()=>{if(!document.getElementById('proof-title').textContent.toLowerCase().includes('verified'))return;setStage(5,'resolved');storyState.textContent='VERIFIED';document.getElementById('story-line-3').textContent='CARAPACE reproduced the fault and independently verified the smallest safe repair.';document.getElementById('incident-status').textContent='Mismatch contained · candidate repair verified';document.getElementById('contract-status').textContent='MISMATCH → MATCH under deterministic replay';heroRun.disabled=false;heroRun.textContent='Run another live story';note.textContent='Complete · human approval remains required'}).observe(document.getElementById('proof-title'),{childList:true,subtree:true});
motionSwitch.addEventListener('click',()=>{ambient=!ambient;motionSwitch.setAttribute('aria-checked',String(ambient));if(window.carapaceScene)window.carapaceScene.ambient=ambient});document.querySelector('.review-link').addEventListener('click',()=>document.getElementById('results').classList.add('visible'));fetch('/api/ai/status').then(r=>r.json()).then(d=>document.getElementById('ai-provenance').textContent=`${d.mode} · ${d.model} · evidence bounded`).catch(()=>document.getElementById('ai-provenance').textContent='AI unavailable · verifier remains active');
try{const THREE=await import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.min.js'),canvas=document.getElementById('assurance-canvas'),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,0,10);const pts=[[-7,-.2,0],[-5,0,.1],[-3,.16,0],[-1,-.13,.1],[1,.12,0],[3,-.03,.1],[5,.08,0],[7,0,0]],curve=a=>new THREE.CatmullRomCurve3(a.map(p=>new THREE.Vector3(...p))),tube=(p,c,r,o)=>new THREE.Mesh(new THREE.TubeGeometry(curve(p),200,r,12,false),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,blending:THREE.AdditiveBlending,depthWrite:false}));const cyanGlow=tube(pts,0x34dfff,.22,.14),cyan=tube(pts,0x51edff,.045,.9);scene.add(cyanGlow,cyan);const up=[[1.4,.05,.1],[2.6,.7,.1],[3.8,.58,.08],[5,.1,0]],down=[[1.4,-.05,.1],[2.7,-.68,.1],[3.9,-.55,.08],[5,-.08,0]],reds=[tube(up,0xff4f69,.07,0),tube(down,0xff4f69,.07,0),tube(up,0xff3358,.25,0),tube(down,0xff3358,.25,0)],greens=[tube([[4,-.1,0],[5,-.2,0],[6.2,.02,0],[7,.02,0]],0x48f4c7,.07,0),tube([[4,-.1,0],[5,-.2,0],[6.2,.02,0],[7,.02,0]],0x35eebf,.25,0)];scene.add(...reds,...greens);const dust=new THREE.BufferGeometry(),pos=new Float32Array(900);for(let i=0;i<300;i++){pos[i*3]=(Math.random()-.5)*17;pos[i*3+1]=(Math.random()-.5)*8;pos[i*3+2]=(Math.random()-.5)*5}dust.setAttribute('position',new THREE.BufferAttribute(pos,3));const stars=new THREE.Points(dust,new THREE.PointsMaterial({color:0x78bfff,size:.025,transparent:true,opacity:.6}));scene.add(stars);const state={ambient:true};window.carapaceScene=state;function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas);resize();let last=0;function render(t){requestAnimationFrame(render);const fault=['incident','resolved'].includes(shell.dataset.phase);reds.forEach((m,i)=>m.material.opacity=fault?(i<2?.95:.18):0);greens.forEach((m,i)=>m.material.opacity=shell.dataset.phase==='resolved'?(i===0?.95:.18):0);cyan.material.opacity=fault?.28:.9;cyanGlow.material.opacity=fault?.05:.14;if(state.ambient){stars.rotation.y+=(t-last)*.000012}last=t;renderer.render(scene,camera)}render(0)}catch(e){console.info('3D fallback active',e)}
</script>
"""
