"""Single-page development console for the Financial Friday sandbox."""

FINANCIAL_FRIDAY_HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Financial Friday safely plans, proves and executes bounded financial tasks in an artificial-money sandbox.">
  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22><circle cx=%2232%22 cy=%2232%22 r=%2228%22 fill=%22%2306d7ff%22/><circle cx=%2232%22 cy=%2232%22 r=%2218%22 fill=%22%23030b16%22/><text x=%2232%22 y=%2240%22 text-anchor=%22middle%22 font-family=%22Arial%22 font-size=%2224%22 font-weight=%22900%22 fill=%22%23bff7ff%22>F</text></svg>">
  <title>Financial Friday · AI financial operator</title>
  <style>
    :root{
      color-scheme:dark;--bg:#080b10;--panel:#10151d;--panel2:#151b24;--line:#27303d;
      --ink:#f4f7fb;--muted:#98a4b5;--lime:#c7ff68;--blue:#79a7ff;--cyan:#63e7e1;
      --red:#ff707d;--amber:#ffc969;--radius:20px;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif
    }
    *{box-sizing:border-box}html{background:var(--bg)}body{margin:0;color:var(--ink);background:radial-gradient(circle at 70% -20%,#1c2a38 0,transparent 35%),var(--bg);min-height:100vh}
    button,textarea,select,input{font:inherit}button{cursor:pointer}button:focus-visible,textarea:focus-visible,select:focus-visible,input:focus-visible,a:focus-visible{outline:3px solid rgba(121,167,255,.55);outline-offset:3px}
    .shell{width:min(1320px,calc(100% - 32px));margin:auto}.topbar{height:74px;border-bottom:1px solid var(--line);background:rgba(8,11,16,.84);backdrop-filter:blur(18px);position:sticky;top:0;z-index:20}
    .topbar .shell{height:100%;display:flex;align-items:center;gap:18px}.mark{width:36px;height:36px;border-radius:12px;background:var(--lime);color:#111;display:grid;place-items:center;font-weight:950;box-shadow:0 0 28px rgba(199,255,104,.18)}
    .brand{font-size:15px;font-weight:850;letter-spacing:-.01em}.brand small{display:block;color:var(--muted);font-weight:550;font-size:11px;margin-top:2px}.top-spacer{flex:1}.pill{display:flex;align-items:center;gap:8px;border:1px solid var(--line);padding:8px 11px;border-radius:999px;color:var(--muted);font-size:12px;background:#0d1218}.dot{width:7px;height:7px;border-radius:50%;background:var(--cyan);box-shadow:0 0 10px var(--cyan)}
    .layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:18px;padding:22px 0 44px}.sidebar,.workspace{border:1px solid var(--line);background:rgba(15,20,28,.88);border-radius:var(--radius)}
    .sidebar{padding:20px;align-self:start;position:sticky;top:96px}.eyebrow{color:var(--lime);font-size:10px;font-weight:850;letter-spacing:.15em;text-transform:uppercase}.sidebar h1{font-size:24px;line-height:1.12;margin:9px 0 8px;letter-spacing:-.035em}.sidebar>p{color:var(--muted);font-size:13px;line-height:1.55;margin:0 0 19px}
    .label{font-size:11px;font-weight:800;color:#dfe5ee;margin-bottom:8px;display:block}.goal,.field{width:100%;resize:vertical;border:1px solid #303b4a;border-radius:12px;background:#0a0f15;color:#dce4ef;padding:11px 12px;line-height:1.45;font-size:12px}.goal{min-height:100px}.goal-note{font-size:10px;color:#748095;line-height:1.45;margin:7px 0 12px}.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.form-grid label{font-size:10px;color:var(--muted)}.form-grid .field{margin-top:5px}.inline-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.live-card{border-color:#334453!important;background:linear-gradient(135deg,rgba(99,231,225,.045),#0c1118 48%)!important}.voice{border-color:rgba(99,231,225,.4)!important;color:var(--cyan)!important}.live-state{margin-top:12px;border-left:2px solid var(--blue);padding-left:11px;color:var(--muted);font-size:12px;line-height:1.5}
    .scenario-list{display:grid;gap:7px}.scenario{width:100%;text-align:left;border:1px solid transparent;background:transparent;color:#b7c0ce;padding:11px 12px;border-radius:13px;display:grid;grid-template-columns:27px 1fr;gap:9px;align-items:start}.scenario:hover{background:#161d27}.scenario[aria-pressed="true"]{background:#1a222d;border-color:#3a4656;color:#fff}.scenario-icon{width:27px;height:27px;border-radius:9px;background:#242e3b;display:grid;place-items:center;font-size:12px}.scenario b{font-size:12px;display:block}.scenario small{display:block;color:#7f8b9e;margin-top:3px;line-height:1.3}.sidebar-links{border-top:1px solid var(--line);padding-top:15px;margin-top:18px;display:flex;gap:14px;flex-wrap:wrap}.sidebar-links a{font-size:11px;color:#9ba8bb;text-decoration:none}.sidebar-links a:hover{color:#fff}
    .workspace{min-height:760px;overflow:hidden}.hero{padding:32px 34px 25px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:1fr auto;gap:24px;align-items:end;background:linear-gradient(130deg,rgba(121,167,255,.07),transparent 46%)}.hero h2{font-size:clamp(29px,4vw,45px);letter-spacing:-.052em;line-height:1.02;margin:9px 0 10px;max-width:680px}.hero p{margin:0;color:var(--muted);font-size:14px;line-height:1.55;max-width:690px}.hero strong{color:#fff}
    .run-controls{display:grid;gap:9px;min-width:200px}.planner{border:1px solid var(--line);border-radius:11px;background:#0b1016;color:#dce4ef;padding:9px 11px;font-size:12px}.run{border:0;border-radius:13px;background:var(--lime);color:#10130c;padding:13px 17px;font-weight:900;box-shadow:0 10px 30px rgba(199,255,104,.12)}.run:hover{filter:brightness(1.06);transform:translateY(-1px)}.run:disabled{opacity:.58;cursor:wait;transform:none}.scope{font-size:10px;color:#778396;text-align:center}
    .body{padding:25px 34px 34px;display:flex;flex-direction:column}.promise{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:22px;order:1}.promise div{border:1px solid var(--line);border-radius:15px;background:#0c1118;padding:14px}.promise span{font-size:10px;color:#7f8a9a;display:block;margin-bottom:5px}.promise b{font-size:13px;font-weight:740}.promise i{color:var(--lime);font-style:normal;margin-right:6px}
    .assurance-board{border:1px solid #2d3948;border-radius:20px;background:linear-gradient(145deg,rgba(121,167,255,.055),rgba(7,11,16,.75) 58%);padding:20px;margin-bottom:22px;overflow:hidden;order:2}.assurance-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:16px}.assurance-head h3{font-size:16px;margin:5px 0 0}.assurance-head p{font-size:11px;color:var(--muted);margin:0;max-width:440px;line-height:1.5;text-align:right}.pipeline{position:relative;display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.pipeline:before{content:"";position:absolute;left:8%;right:8%;top:22px;height:1px;background:#293543}.stage{position:relative;border:1px solid var(--line);border-radius:15px;padding:13px 12px 14px;background:#0b1016;min-height:112px;transition:.3s ease;z-index:1}.stage .number{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;font-size:9px;color:#708096;background:#121a24;border:1px solid #344151}.stage b{display:block;font-size:11px;margin:13px 0 5px}.stage small{display:block;color:#788598;line-height:1.35;font-size:9px}.stage em{display:block;color:#738096;font-size:9px;margin-top:8px;font-style:normal}.stage.active{border-color:var(--blue);box-shadow:0 0 0 1px rgba(121,167,255,.22),0 12px 35px rgba(0,0,0,.2);transform:translateY(-3px)}.stage.active .number{background:var(--blue);border-color:var(--blue);color:#07101f;box-shadow:0 0 15px rgba(121,167,255,.45)}.stage.done{border-color:rgba(99,231,225,.45);background:linear-gradient(180deg,rgba(99,231,225,.06),#0b1016)}.stage.done .number{color:#07110f;background:var(--cyan);border-color:var(--cyan)}.stage.blocked{border-color:rgba(255,112,125,.55);background:linear-gradient(180deg,rgba(255,112,125,.06),#0b1016)}.stage.blocked .number{color:#170609;background:var(--red);border-color:var(--red)}.stage.skipped{opacity:.48}.stage.retry{border-color:rgba(255,201,105,.55)}
    .briefing{display:none;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:14px;margin-bottom:15px}.briefing.visible{display:grid}.brief-main{border:1px solid #354353;border-radius:18px;background:linear-gradient(135deg,#111925,#0b1016);padding:20px}.brief-label{display:flex;align-items:center;gap:8px;color:var(--cyan);font-size:10px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.brief-pulse{width:8px;height:8px;border-radius:50%;background:var(--cyan);box-shadow:0 0 14px var(--cyan)}.brief-main h3{font-size:22px;letter-spacing:-.03em;margin:13px 0 7px}.brief-main p{color:#aab5c4;font-size:13px;line-height:1.6;margin:0}.brief-side{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metric{border:1px solid #293441;border-radius:14px;padding:12px;background:#0a0f15}.metric span{display:block;color:#718095;font-size:9px;text-transform:uppercase;letter-spacing:.09em}.metric b{display:block;font-size:15px;margin-top:7px;overflow-wrap:anywhere}.metric small{display:block;color:#758195;font-size:9px;margin-top:3px}.result-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px}.result-toolbar span{font-size:11px;color:var(--muted)}
    .empty{border:1px dashed #303a47;border-radius:18px;padding:40px 24px;text-align:center;background:#0b0f15;order:3;margin-bottom:22px}.empty .orb{width:62px;height:62px;border:1px solid #364253;border-radius:50%;display:grid;place-items:center;margin:0 auto 15px;font-size:22px;color:var(--lime);background:radial-gradient(circle,#1f2b25,#0c1117 68%)}.empty h3{font-size:17px;margin:0 0 7px}.empty p{color:var(--muted);font-size:13px;margin:0 auto;max-width:470px;line-height:1.55}
    .result{display:none;order:3;margin-bottom:22px}.result.visible{display:block}.live-card{order:4}.watch-card{order:5}.verdict{border:1px solid var(--line);border-radius:18px;padding:19px 20px;display:flex;gap:15px;align-items:flex-start;margin-bottom:15px;background:#0b1016}.verdict-icon{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:#202a35;flex:0 0 auto}.verdict h3{margin:0 0 5px;font-size:18px}.verdict p{margin:0;color:var(--muted);line-height:1.5;font-size:13px}.verdict.good{border-color:rgba(99,231,225,.4)}.verdict.good .verdict-icon{background:rgba(99,231,225,.13);color:var(--cyan)}.verdict.bad{border-color:rgba(255,112,125,.45)}.verdict.bad .verdict-icon{background:rgba(255,112,125,.12);color:var(--red)}.verdict.warn{border-color:rgba(255,201,105,.4)}.verdict.warn .verdict-icon{background:rgba(255,201,105,.12);color:var(--amber)}
    .result-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:15px}.card{border:1px solid var(--line);background:#0c1118;border-radius:17px;padding:18px}.card-head{display:flex;justify-content:space-between;align-items:start;gap:10px;margin-bottom:15px}.card h3{font-size:13px;margin:0}.badge{font-size:9px;letter-spacing:.08em;text-transform:uppercase;padding:5px 7px;border-radius:999px;background:#202834;color:#a9b4c5}.steps,.checks,.events{list-style:none;margin:0;padding:0;display:grid;gap:8px}.steps li,.checks li{display:grid;grid-template-columns:27px 1fr;gap:9px;align-items:center;border:1px solid #222b37;border-radius:11px;padding:9px 10px;font-size:11px;color:#c6cfda}.steps .step-icon,.checks .step-icon{width:27px;height:27px;border-radius:8px;background:#19222d;display:grid;place-items:center;color:var(--cyan);font-size:10px}.checks li{grid-template-columns:18px 1fr;padding:8px 10px}.checks .step-icon{width:18px;height:18px;background:transparent;color:var(--lime)}
    .facts{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fact{border:1px solid #222b37;border-radius:11px;padding:10px}.fact span{display:block;color:#778397;font-size:9px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px}.fact b{font-size:12px;overflow-wrap:anywhere}.receipt{margin-top:15px}.receipt code{display:block;background:#080c11;border:1px solid #222b37;border-radius:12px;padding:12px;font-size:10px;color:#99a7b9;overflow-wrap:anywhere;line-height:1.5}.activity{margin-top:15px}.events li{border-left:2px solid #334052;padding:2px 0 10px 12px}.events b{font-size:11px;display:block}.events small{font-size:10px;color:#7f8b9c;line-height:1.45}.technical{margin-top:15px}.technical summary{cursor:pointer;font-size:11px;color:#9faabd}.technical pre{background:#070b10;border-radius:12px;padding:13px;white-space:pre-wrap;overflow-wrap:anywhere;font:10px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;color:#92a0b3;max-height:330px;overflow:auto}
    .toast{position:fixed;right:22px;bottom:22px;border:1px solid #3a4655;background:#151b24;color:#e8edf4;padding:12px 14px;border-radius:12px;font-size:12px;box-shadow:0 18px 55px #000;transform:translateY(25px);opacity:0;pointer-events:none;transition:.2s}.toast.show{transform:none;opacity:1}
    /* FRIDAY command-centre visual system. The execution and trust model remain unchanged. */
    :root{--bg:#020710;--panel:#06101b;--panel2:#081725;--line:rgba(64,189,229,.24);--ink:#e9fbff;--muted:#7f9daf;--lime:#29e5ff;--blue:#41a7ff;--cyan:#61f4ff;--radius:8px}
    body{background:radial-gradient(circle at 72% 12%,rgba(0,168,255,.14),transparent 27%),radial-gradient(circle at 15% 65%,rgba(42,89,180,.11),transparent 32%),#020710;background-attachment:fixed}
    body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.26;background-image:linear-gradient(rgba(35,173,220,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(35,173,220,.08) 1px,transparent 1px);background-size:40px 40px;mask-image:linear-gradient(to bottom,black,transparent 90%)}
    body:after{content:"";position:fixed;left:0;right:0;top:-15%;height:26%;pointer-events:none;background:linear-gradient(transparent,rgba(74,226,255,.035),transparent);animation:scan 8s linear infinite}
    @keyframes scan{to{transform:translateY(520%)}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes reverse-spin{to{transform:rotate(-360deg)}}@keyframes core-pulse{50%{box-shadow:0 0 16px #61f4ff,0 0 70px rgba(52,199,255,.5),inset 0 0 28px rgba(47,205,255,.28)}}@keyframes bars{50%{transform:scaleY(.35);opacity:.5}}
    .topbar{height:72px;border-bottom:1px solid rgba(69,207,255,.35);background:rgba(1,7,15,.82);box-shadow:0 6px 35px rgba(0,0,0,.42)}.mark{border-radius:50%;background:radial-gradient(circle,#bff9ff 0 8%,#1fd4ff 9% 24%,#041323 26% 48%,#1fd4ff 50% 54%,#020813 56%);color:transparent;box-shadow:0 0 24px rgba(42,217,255,.48);position:relative}.mark:after{content:"";position:absolute;inset:-5px;border:1px solid rgba(74,229,255,.55);border-left-color:transparent;border-radius:50%;animation:spin 4s linear infinite}.brand{text-transform:uppercase;letter-spacing:.13em;color:#dffaff}.brand small{letter-spacing:.05em;color:#5fa6bd}.pill{border-color:rgba(62,198,239,.28);background:rgba(4,17,28,.72);border-radius:4px;text-transform:uppercase;letter-spacing:.08em;font-size:10px}.dot{background:#55f5ff;box-shadow:0 0 14px #55f5ff}
    .layout{grid-template-columns:310px minmax(0,1fr);gap:14px}.sidebar,.workspace{background:linear-gradient(145deg,rgba(5,17,29,.94),rgba(2,9,18,.91));border-color:rgba(64,189,229,.27);border-radius:8px;box-shadow:inset 0 0 45px rgba(10,113,160,.035),0 20px 70px rgba(0,0,0,.34)}.sidebar{clip-path:polygon(0 0,94% 0,100% 22px,100% 100%,0 100%)}.eyebrow{color:#58eaff;letter-spacing:.22em;text-shadow:0 0 12px rgba(61,231,255,.42)}.sidebar h1{font-weight:550;letter-spacing:-.02em;color:#dffaff}.goal,.field,.planner{background:rgba(1,10,18,.78);border-color:rgba(69,190,226,.28);border-radius:4px}.goal:focus,.field:focus,.planner:focus{border-color:#4be5ff;box-shadow:0 0 0 1px rgba(75,229,255,.25),0 0 18px rgba(27,176,224,.12)}
    .scenario{border-radius:4px;border-left:2px solid transparent}.scenario:hover{background:rgba(29,147,191,.09)}.scenario[aria-pressed="true"]{background:linear-gradient(90deg,rgba(38,176,224,.15),rgba(8,25,39,.7));border-color:rgba(69,218,255,.5);box-shadow:inset 4px 0 18px rgba(38,208,255,.08)}.scenario-icon{border-radius:50%;background:rgba(25,100,134,.22);border:1px solid rgba(71,218,255,.24);color:#64edff}
    .hero{min-height:340px;padding:34px 38px;border-color:rgba(60,190,231,.24);grid-template-columns:minmax(0,1fr) 280px;grid-template-rows:220px auto;align-items:center;position:relative;background:radial-gradient(circle at 80% 42%,rgba(17,139,202,.18),transparent 29%),linear-gradient(110deg,rgba(24,102,143,.09),transparent 50%)}.hero h2{font-weight:430;max-width:700px;text-transform:uppercase;letter-spacing:-.02em;font-size:clamp(30px,4vw,50px)}.hero h2 strong,.hero .accent{color:#68edff;text-shadow:0 0 22px rgba(60,220,255,.28)}.hero p{color:#89aabd}.hero-main{position:relative;z-index:2;grid-row:1/3}.system-line{display:flex;gap:14px;flex-wrap:wrap;margin-top:18px}.system-line span{font:9px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em;text-transform:uppercase;color:#70b4c8;border-left:1px solid #28caef;padding-left:8px}
    .core-console{display:grid;place-items:center;position:relative;height:220px}.core-ring{position:absolute;border-radius:50%;border:1px solid rgba(67,220,255,.42)}.core-ring.r1{width:188px;height:188px;border-style:dashed;animation:spin 16s linear infinite}.core-ring.r2{width:146px;height:146px;border-width:2px;border-top-color:transparent;border-bottom-color:#1e7ca7;animation:reverse-spin 9s linear infinite}.core-ring.r3{width:105px;height:105px;border-left-color:transparent;border-right-color:transparent;animation:spin 5s linear infinite}.core-center{width:72px;height:72px;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle,#d8fdff 0 5%,#35dfff 7% 18%,#061a2a 20% 51%,#28cbef 53% 56%,#020913 59%);box-shadow:0 0 14px #61f4ff,0 0 54px rgba(52,199,255,.35),inset 0 0 28px rgba(47,205,255,.2);animation:core-pulse 2.8s ease-in-out infinite}.core-center span{font:800 13px ui-monospace,monospace;letter-spacing:.16em;color:#e4fdff;text-shadow:0 0 10px #fff}.core-state{position:absolute;bottom:2px;text-align:center}.core-state b{display:block;font:700 10px ui-monospace,monospace;letter-spacing:.18em;color:#68efff}.core-state small{font-size:9px;color:#54879a}.wave{position:absolute;left:5px;right:5px;top:50%;display:flex;justify-content:space-between;align-items:center;opacity:.38}.wave i{width:2px;height:18px;background:#56edff;box-shadow:0 0 6px #56edff;animation:bars 1.1s ease-in-out infinite}.wave i:nth-child(3n){height:34px;animation-delay:.25s}.wave i:nth-child(2n){height:25px;animation-delay:.5s}
    .run-controls{position:static;width:230px;z-index:4;grid-column:2;grid-row:2;justify-self:center}.run-controls:before{content:"SELECTED SAFETY DEMO";display:block;text-align:center;color:#5290a5;font:8px ui-monospace,monospace;letter-spacing:.14em}.run{border-radius:3px;background:linear-gradient(90deg,#0fc2ea,#71f5ff);color:#021019;box-shadow:0 0 0 1px rgba(122,246,255,.4),0 0 24px rgba(29,199,235,.18);text-transform:uppercase;letter-spacing:.08em;font-size:11px}.run:hover{box-shadow:0 0 0 1px #aafaff,0 0 30px rgba(29,217,255,.35)}
    .promise div,.card,.assurance-board,.empty,.verdict,.brief-main,.metric,.fact{border-radius:5px;background:linear-gradient(145deg,rgba(7,24,38,.88),rgba(3,12,22,.94));border-color:rgba(66,190,229,.25)}.promise div{position:relative;overflow:hidden}.promise div:after{content:"";position:absolute;right:-8px;top:-8px;width:24px;height:24px;border-top:1px solid #4cdcf8;transform:rotate(45deg)}
    .assurance-board{box-shadow:inset 0 0 45px rgba(16,139,179,.04)}.pipeline:before{background:linear-gradient(90deg,transparent,#2fd8ff,#2fd8ff,transparent);box-shadow:0 0 10px rgba(47,216,255,.3)}.stage{border-radius:3px;background:rgba(2,12,21,.9);clip-path:polygon(0 0,calc(100% - 10px) 0,100% 10px,100% 100%,0 100%)}.stage.done{background:linear-gradient(180deg,rgba(20,167,201,.15),rgba(2,14,24,.93));box-shadow:inset 0 0 22px rgba(48,217,255,.05)}.stage .number{border-radius:50%;background:#04101c}.stage.active{box-shadow:0 0 0 1px rgba(82,228,255,.3),0 0 28px rgba(39,181,229,.15)}
    .brief-main{position:relative;overflow:hidden}.brief-main:after{content:"FRIDAY // VERIFIED INTELLIGENCE";position:absolute;right:16px;top:12px;color:rgba(99,226,255,.18);font:8px ui-monospace,monospace;letter-spacing:.16em}.badge{border-radius:3px;background:rgba(33,105,135,.22);color:#83ddef;border:1px solid rgba(72,192,230,.18)}.technical pre,.receipt code{background:rgba(0,7,13,.9);border-color:rgba(47,173,211,.24);color:#76adbd}.live-card{box-shadow:inset 0 0 38px rgba(27,161,201,.04)!important}.voice{box-shadow:0 0 16px rgba(58,221,244,.06)}
    .live-card{order:1!important;padding:22px 24px!important}.promise{order:2}.assurance-board{order:3}.empty,.result{order:4}.watch-card{order:5}.empty{display:none!important}.command-prompt{display:grid;grid-template-columns:auto 1fr;gap:13px;align-items:start}.command-avatar{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(80,225,255,.48);background:radial-gradient(circle,#54ebff 0 8%,#07233a 10% 55%,#18b9de 57% 60%,#03101b 62%);box-shadow:0 0 20px rgba(55,218,255,.18);font:700 9px ui-monospace,monospace;color:#dffcff}.command-copy h3{font-size:17px;margin:0 0 5px}.command-copy p{margin:0 0 14px;color:#83a4b5;font-size:12px}.command-input{min-height:82px;border-color:rgba(74,218,251,.35);font-size:13px}.provider-setup,.mission-details,.watch-card{border:1px solid rgba(66,190,229,.2);border-radius:4px}.provider-setup{margin-top:16px;padding:11px 13px;background:rgba(0,9,16,.48)}.provider-setup summary,.mission-details>summary,.watch-card>summary{cursor:pointer;color:#74cfe4;font:700 10px ui-monospace,monospace;letter-spacing:.11em;text-transform:uppercase}.provider-setup[open] summary,.mission-details[open]>summary,.watch-card[open]>summary{margin-bottom:14px}.mission-details{margin-top:14px;padding:14px;background:rgba(0,8,15,.4)}.mission-details .result-grid{margin-top:14px}.watch-card{padding:16px 18px!important}.watch-card>summary{display:flex;justify-content:space-between;align-items:center;list-style:none}.watch-card>summary::-webkit-details-marker{display:none}.watch-card>summary:after{content:"OPEN";color:#4ddff7;border:1px solid rgba(74,219,247,.25);padding:4px 7px}.watch-card[open]>summary:after{content:"CLOSE"}.result-toolbar{margin-top:11px}.assurance-board{padding:16px 18px}.stage{min-height:92px}.stage small{display:none}.stage b{margin-top:10px}
    @media(max-width:1040px){.hero{grid-template-columns:1fr 220px}.core-console{transform:scale(.86)}.run-controls{position:static;width:auto;grid-column:1/-1;grid-template-columns:1fr 1fr}.scope{grid-column:1/-1}}
    @media(max-width:760px){.hero{grid-template-columns:1fr}.core-console{height:190px}.layout{grid-template-columns:1fr}.sidebar{clip-path:none}.run-controls{grid-template-columns:1fr}.hero h2{text-align:center}.hero-main{text-align:center}.system-line{justify-content:center}}
    @media(max-width:1040px){.pipeline{grid-template-columns:repeat(3,1fr)}.pipeline:before{display:none}.briefing{grid-template-columns:1fr}}
    @media(max-width:920px){.layout{grid-template-columns:1fr}.sidebar{position:static}.scenario-list{grid-template-columns:1fr 1fr}.hero{grid-template-columns:1fr}.run-controls{grid-template-columns:1fr 1fr}.scope{grid-column:1/-1}.result-grid{grid-template-columns:1fr}}
    @media(max-width:620px){.shell{width:min(100% - 18px,1320px)}.pill.optional{display:none}.layout{padding-top:10px}.sidebar,.workspace{border-radius:16px}.hero,.body{padding:22px 18px}.scenario-list,.promise,.pipeline{grid-template-columns:1fr}.run-controls{grid-template-columns:1fr}.pipeline{padding-left:0}.stage{min-height:auto}.topbar{height:64px}.facts{grid-template-columns:1fr}.assurance-head{align-items:flex-start;flex-direction:column}.assurance-head p{text-align:left}.brief-side{grid-template-columns:1fr 1fr}}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
  </style>
</head>
<body>
  <header class="topbar"><div class="shell">
    <div class="mark" aria-hidden="true">F</div><div class="brand">F.R.I.D.A.Y.<small>Financial Reasoning, Intelligence &amp; Delegated Action for You</small></div>
    <div class="top-spacer"></div><div class="pill"><span class="dot"></span><span id="ai-status">Connecting…</span></div><div class="pill optional">Core online · sandbox</div>
  </div></header>
  <main class="shell layout">
    <aside class="sidebar">
      <div class="eyebrow">Operator mandate</div><h1>Set the boundary.<br>Friday handles the mission.</h1>
      <p>Friday plans the route, proves it stays inside your permission, and acts only through a restricted test provider.</p>
      <label class="label" for="goal">Your standing instruction</label>
      <textarea class="goal" id="goal">Track my verified household bills, protect ₹10,000, and never create subscriptions.</textarea>
      <div class="form-grid" style="grid-template-columns:1fr 1fr"><label>Protected balance<input class="field" id="reserve" type="number" min="0" step="100" value="10000"></label><label>Automatic limit<input class="field" id="auto-limit" type="number" min="0" step="100" value="5000"></label></div>
      <label style="display:flex;gap:8px;align-items:center;margin-top:10px;font-size:11px;color:var(--muted)"><input id="auto-execute" type="checkbox"> Automatically execute verified artificial-money bills</label>
      <div class="inline-actions"><button class="planner" id="save-mandate" type="button">Save instruction</button></div>
      <p class="goal-note">These limits persist for this tenant. Real providers and real accounts are not connected.</p>
      <span class="label">Try a real safety condition</span><div id="scenarios" class="scenario-list" aria-label="Sandbox scenarios"></div>
      <div class="sidebar-links"><a href="/operations">Earlier operations lab</a><a href="/payment-check">Payment check</a><a href="http://localhost:8080/docs" target="_blank" rel="noopener">API docs ↗</a></div>
    </aside>
    <section class="workspace" aria-labelledby="workspace-title">
      <div class="hero"><div class="hero-main"><div class="eyebrow">Friday online</div><h2 id="workspace-title">Good morning.<br><span class="accent">What can I handle?</span></h2><p id="scenario-copy">Give Friday an outcome. It will understand the request, verify the evidence and act only inside your permission.</p><div class="system-line"><span>Identity secured</span><span>Safety kernel ready</span><span>Evidence connected</span></div></div>
        <div class="core-console" aria-label="Friday AI core"><div class="wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="core-ring r1"></div><div class="core-ring r2"></div><div class="core-ring r3"></div><div class="core-center"><span>FRIDAY</span></div><div class="core-state"><b id="core-state">STANDING BY</b><small id="core-detail">Awaiting your command</small></div></div>
        <div class="run-controls"><select class="planner" id="planner" aria-label="Planning engine"><option value="configured">Gemini / configured AI</option><option value="local">Local rules comparison</option></select><button class="run" id="run" type="button">Run selected demo</button><div class="scope">Restricted sandbox · no real bank access</div></div>
      </div>
      <div class="body">
        <article class="card live-card" style="margin-bottom:22px">
          <div class="card-head"><div class="eyebrow">Direct command</div><span class="badge" id="live-mode">Listening</span></div>
          <div class="command-prompt"><div class="command-avatar">F</div><div class="command-copy"><h3>Talk to Friday</h3><p>Paste a bill message, payment request or voice transcript. Friday will find the important details and tell you only what matters.</p>
          <label class="label" for="live-input">What should Friday handle?</label><textarea class="goal command-input" id="live-input">Message from TN Power: Bill LIVE-1001 for ₹2,499 is due. Payee: tnpower@upi</textarea>
          <div class="inline-actions"><button class="run" id="check-live" type="button">Handle this safely</button><button class="planner voice" id="speak-live" type="button">◉ Speak</button></div><div class="live-state" id="live-result">Ready when you are.</div></div></div>
          <details class="provider-setup"><summary>Demo provider setup</summary><div class="form-grid"><label>Bill reference<input class="field" id="provider-reference" value="LIVE-1001"></label><label>Amount in rupees<input class="field" id="provider-amount" type="number" min="1" step=".01" value="2499"></label><label>Verified payee<input class="field" id="provider-payee" value="tnpower@upi"></label></div><div class="inline-actions"><button class="planner" id="publish-bill" type="button">Publish test bill</button></div></details>
        </article>
        <details class="card watch-card" style="margin-bottom:22px">
          <summary>Proactive bill monitoring <span class="badge" id="watch-status">Loading</span></summary>
          <div class="card-head"><h3>Friday keeps an eye on your bills</h3></div>
          <p>Enable the sandbox feed once. Friday checks incoming sample bills in the background, even when this page is closed while Docker runs. It prepares tasks and in-app due reminders; payments still require your decision.</p>
          <button class="run" id="watch-toggle" type="button" disabled>Enable bill monitoring</button>
          <button class="planner" id="deliver-bill" type="button">Deliver selected sample bill</button>
          <p id="inbox-error" role="status"></p><ul class="events" id="bill-inbox" aria-live="polite"></ul>
          <small>The earlier fixed scenarios remain as regression demonstrations. Use the live input card above for a new, dynamic task.</small>
        </details>
        <div class="promise" aria-label="Delegation limits"><div><span>Your boundary</span><b><i>✓</i>One-time tasks only</b></div><div><span>Automatic ceiling</span><b id="visible-limit"><i>✓</i>₹5,000.00</b></div><div><span>Never allowed</span><b><i>✓</i>Fee or subscription</b></div></div>
        <section class="assurance-board" aria-labelledby="journey-title">
          <div class="assurance-head"><div><div class="eyebrow">Live assurance journey</div><h3 id="journey-title">See Friday think, prove and act</h3></div><p id="journey-copy">Gemini can propose. Only verified backend evidence can turn a stage green or permit an action.</p></div>
          <div class="pipeline" aria-label="Financial Friday execution pipeline">
            <div class="stage" data-stage="understand"><span class="number">1</span><b>Understand</b><small>Turn the request into a precise financial goal.</small><em>Waiting for input</em></div>
            <div class="stage" data-stage="ground"><span class="number">2</span><b>Ground evidence</b><small>Match provider, payee, amount and currency.</small><em>No claim trusted yet</em></div>
            <div class="stage" data-stage="plan"><span class="number">3</span><b>Plan with AI</b><small>Gemini proposes bounded typed actions.</small><em>Proposal only</em></div>
            <div class="stage" data-stage="prove"><span class="number">4</span><b>Prove safety</b><small>Independent code tests rules and hostile mutations.</small><em>Deterministic gate</em></div>
            <div class="stage" data-stage="act"><span class="number">5</span><b>Act or recover</b><small>Execute once, reconcile, or stop safely.</small><em>No action yet</em></div>
          </div>
        </section>
        <div class="empty" id="empty"><div class="orb">✦</div><h3>Friday has not acted yet</h3><p>Select a test situation on the left. The interface will show the plan, the proof and the outcome—not just an AI answer.</p></div>
        <div class="result" id="result" aria-live="polite">
          <section class="briefing" id="briefing"><div class="brief-main"><div class="brief-label"><span class="brief-pulse"></span>Friday briefing</div><h3 id="brief-title">Task handled</h3><p id="brief-copy"></p></div><div class="brief-side"><div class="metric"><span>AI calls</span><b id="metric-ai">0</b><small id="metric-ai-note">Not needed</small></div><div class="metric"><span>Safety gate</span><b id="metric-proof">—</b><small>Independent code</small></div><div class="metric"><span>Money effects</span><b id="metric-effects">0</b><small>Artificial sandbox</small></div><div class="metric"><span>Run mode</span><b id="metric-mode">—</b><small id="metric-model">—</small></div></div></section>
          <div class="result-toolbar"><span id="run-reference">No run selected</span><span>Technical evidence remains inspectable below</span></div>
          <div class="verdict" id="verdict"><div class="verdict-icon" id="verdict-icon">✓</div><div><h3 id="verdict-title"></h3><p id="verdict-copy"></p></div></div>
          <details class="mission-details"><summary>Show how Friday verified this</summary><div class="result-grid">
            <article class="card"><div class="card-head"><h3>Verified action program</h3><span class="badge" id="model-badge">AI proposal</span></div><ol class="steps" id="steps"></ol><div class="activity"><div class="card-head"><h3>What Friday actually did</h3></div><ul class="events" id="events"></ul></div></article>
            <div><article class="card"><div class="card-head"><h3>Independent safety proof</h3><span class="badge" id="proof-badge">Not run</span></div><div class="facts" id="facts"></div><ul class="checks" id="checks"></ul></article><article class="card receipt"><div class="card-head"><h3>Outcome evidence</h3><span class="badge" id="receipt-badge">Sandbox</span></div><code id="receipt">No receipt was created.</code></article></div>
          </div><details class="technical"><summary>Open complete technical evidence</summary><pre id="raw"></pre></details></details>
        </div>
      </div>
    </section>
  </main>
  <div class="toast" id="toast" role="status"></div>
  <script>
    const $=id=>document.getElementById(id);let selected='genuine-bill';let catalogue=[];let liveSource='MESSAGE';
    const labels={
      'genuine-bill':['✓','Pay a genuine bill'],
      'subscription-trap':['↻','Avoid a subscription trap'],
      'recurring-only':['⊘','Refuse an unsafe option'],
      'recipient-swap':['⇄','Catch a changed recipient'],
      'unknown-outcome':['?','Recover after a timeout']
    };
    const nice=s=>String(s||'').toLowerCase().replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
    const money=n=>'₹'+((Number(n)||0)/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
    function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
    function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400);}
    function setCore(state,detail){$('core-state').textContent=state;$('core-detail').textContent=detail;}
    function selectScenario(id){selected=id;document.querySelectorAll('.scenario').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.id===id)));const item=catalogue.find(x=>x.id===id);$('scenario-copy').textContent=item?.description||'';$('result').classList.remove('visible');$('briefing').classList.remove('visible');$('empty').hidden=false;resetStages();setCore('MISSION LOADED',item?.name||'Ready for protected execution');}
    function stage(name,state,note){const el=document.querySelector(`[data-stage="${name}"]`);if(!el)return;el.classList.remove('active','done','blocked','skipped','retry');if(state)el.classList.add(state);if(note)el.querySelector('em').textContent=note;}
    function resetStages(){const defaults={understand:'Waiting for input',ground:'No claim trusted yet',plan:'Proposal only',prove:'Deterministic gate',act:'No action yet'};document.querySelectorAll('.stage').forEach(el=>{el.classList.remove('active','done','blocked','skipped','retry');el.querySelector('em').textContent=defaults[el.dataset.stage];});$('journey-copy').textContent='Gemini can propose. Only verified backend evidence can turn a stage green or permit an action.';}
    function pulse(name,note){document.querySelectorAll('.stage').forEach(el=>el.classList.remove('active'));stage(name,'active',note);}
    function fillStages(result){
      resetStages();const events=result.events||[];const types=events.map(event=>event.type);const deterministicHold=types.includes('DETERMINISTIC_EVIDENCE_HOLD');const passed=Boolean(result.program?.verification?.passed);const attacks=result.program?.adversarial_checks||[];const calls=Number(result.provenance?.successful_model_calls||0);
      stage('understand','done','Goal structured');
      stage('ground',deterministicHold?'blocked':'done',deterministicHold?'Contradiction found':'Evidence matched');
      if(deterministicHold)stage('plan','skipped','AI not called');else stage('plan',calls>0?'done':'done',calls>0?'Gemini responded':'Local baseline');
      if(deterministicHold)stage('prove','done','Stopped before AI');else stage('prove',passed&&attacks.every(x=>x.rejected)?'done':'blocked',passed?'Hostile changes rejected':'Program rejected');
      stage('act',result.status==='HELD'?'blocked':'done',result.status==='RECONCILED_COMPLETED'?'Prior result found':result.status==='ALREADY_COMPLETED'?'Duplicate prevented':result.status==='HELD'?'No money moved':'Completed once');
      if(types.includes('AI_PROVIDER_RETRY'))stage('plan','retry','Provider recovered after retry');
      $('journey-copy').textContent=deterministicHold?'Authoritative evidence contradicted the request, so Friday stopped before spending an AI call or touching money.':result.status==='RECONCILED_COMPLETED'?'Friday checked the provider first, found the earlier success and correctly avoided a duplicate retry.':'The visible stages below are reconstructed from this run’s signed backend evidence.';
    }
    function outcomeText(r){
      if(r.status==='COMPLETED_SYNTHETIC')return ['good','Task completed safely','Friday selected an allowed route, the kernel proved it, and exactly one artificial-money payment was recorded.'];
      if(r.status==='ALREADY_COMPLETED')return ['good','Already handled—nothing repeated','Friday found the signed earlier result and did not create another payment.'];
      if(r.status==='RECONCILED_COMPLETED')return ['warn','Previous payment found—no retry sent','The earlier provider outcome was checked first. It had already succeeded, so Friday created no new payment.'];
      const reasons=(r.outcome?.reason||['NO_VERIFIED_PROGRAM']).map(nice).join(' · ');return ['bad','Friday safely refused this task',`The request could not be completed without breaking your permission: ${reasons}. No money moved.`];
    }
    function render(r){
      $('empty').hidden=true;$('result').classList.add('visible');$('briefing').classList.add('visible');fillStages(r);const [tone,title,copy]=outcomeText(r);$('verdict').className='verdict '+tone;$('verdict-icon').textContent=tone==='bad'?'!':tone==='warn'?'↻':'✓';$('verdict-title').textContent=title;$('verdict-copy').textContent=copy;
      setCore(r.status==='HELD'?'THREAT CONTAINED':r.status==='RECONCILED_COMPLETED'?'STATE RECOVERED':'MISSION VERIFIED',r.status==='HELD'?'No financial action permitted':r.status==='RECONCILED_COMPLETED'?'No duplicate action required':'Evidence chain complete');
      const calls=Number(r.provenance?.successful_model_calls||0);const effects=Boolean(r.outcome?.new_payment_created)?1:0;const proof=Boolean(r.program?.verification?.passed);$('brief-title').textContent=title;$('brief-copy').textContent=copy;$('metric-ai').textContent=String(calls);$('metric-ai-note').textContent=calls?'Structured planning':'Not needed or local';$('metric-proof').textContent=r.status==='HELD'?'STOPPED':proof?'PASSED':'CHECKED';$('metric-effects').textContent=String(effects);$('metric-mode').textContent=nice(r.provenance?.mode||'Safety kernel');$('metric-model').textContent=r.provenance?.model||'No model used';$('run-reference').textContent=`Run ${r.run_id} · ${nice(r.status)}`;
      $('model-badge').textContent=`${r.provenance?.mode||'SAFETY_KERNEL'} · ${r.provenance?.model||'deterministic evidence gate'}`;$('steps').replaceChildren();const steps=r.program?.candidate?.steps||[];
      if(!steps.length){const li=node('li','No executable program passed the safety kernel.');li.prepend(node('span','—','step-icon'));$('steps').append(li);}else steps.forEach((step,index)=>{const li=node('li');li.append(node('span',String(index+1).padStart(2,'0'),'step-icon'),node('span',nice(step.action)+(step.option_id?' · '+step.option_id:'')));$('steps').append(li);});
      const verification=r.program?.verification;const attacks=r.program?.adversarial_checks||[];$('proof-badge').textContent=verification?.passed?'Verified':'Execution held';$('facts').replaceChildren();[
        ['Payee',r.goal.payee_id],['Maximum',money(r.goal.max_total_minor)],['New payment',String(Boolean(r.outcome?.new_payment_created))],['Model calls',String(r.provenance.successful_model_calls)]
      ].forEach(([key,value])=>{const box=node('div',undefined,'fact');box.append(node('span',key),node('b',value));$('facts').append(box);});
      $('checks').replaceChildren();if(attacks.length)attacks.forEach(check=>{const li=node('li');li.append(node('span',check.rejected?'✓':'!','step-icon'),node('span',check.name));$('checks').append(li);});else{const li=node('li');li.append(node('span',r.status==='HELD'?'✓':'—','step-icon'),node('span',r.status==='HELD'?'Unsafe execution was prevented':'No adversarial checks reported'));$('checks').append(li);}
      $('events').replaceChildren();(r.events||[]).forEach(event=>{const li=node('li');let detail='';if(event.type==='AI_PROGRAM_PROPOSED')detail=`Attempt ${event.attempt}: ${event.verification.passed?'accepted by the kernel':'rejected by the kernel'}.`;else if(event.type==='RESTRICTED_EXECUTOR_RESULT')detail=event.new_payment?'One artificial-money effect was written and read back.':'No new financial effect was created.';else if(event.type==='RECONCILED_BEFORE_RETRY')detail='Existing provider state was checked before any retry.';else if(event.type==='DETERMINISTIC_EVIDENCE_HOLD')detail='Authoritative evidence contradicted the request. AI and execution were bypassed.';else if(event.type==='AI_PROVIDER_RETRY')detail='A temporary AI-provider failure was retried within the bounded policy.';else detail=event.error_type||'';li.append(node('b',nice(event.type)),node('small',detail));$('events').append(li);});
      const receipt=r.outcome?.receipt;$('receipt-badge').textContent=receipt?'Signed receipt':r.status==='HELD'?'No execution':'Reconciled';$('receipt').textContent=receipt?`Operation ${receipt.payload.operation_id}\n${money(receipt.payload.amount_minor)} · ${receipt.payload.payee_id}\nKey ${receipt.key_id}\nSignature ${receipt.signature.slice(0,34)}…`:r.outcome?.message||'No receipt was created because the safety gate held execution.';
      $('raw').textContent=JSON.stringify(r,null,2);history.replaceState(null,'','#run='+encodeURIComponent(r.run_id));
    }
    async function run(){
      const button=$('run');button.disabled=true;button.textContent='Analysing mission…';setCore('ANALYSING','Reading intent and permission');$('empty').hidden=false;$('result').classList.remove('visible');$('briefing').classList.remove('visible');$('empty').querySelector('h3').textContent='Friday is handling the task';$('empty').querySelector('p').textContent='Follow the live assurance journey above. Friday may complete, recover, or safely stop.';resetStages();pulse('understand','Reading goal and constraints');
      const sequence=[['ground','Resolving trusted evidence'],['plan','Requesting a bounded plan'],['prove','Testing permission and attacks'],['act','Executing or reconciling safely']];let stageIndex=0;const stageTimer=setInterval(()=>{if(stageIndex<sequence.length){pulse(...sequence[stageIndex]);stageIndex+=1;}},650);
      try{const response=await fetch('/api/friday/scenarios/'+encodeURIComponent(selected)+'/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planner:$('planner').value})});const result=await response.json();if(!response.ok)throw new Error(result.detail||'Financial Friday could not complete this run.');render(result);toast(result.status==='HELD'?'Unsafe action safely held':'Sandbox run complete');}
      catch(error){resetStages();stage('act','blocked','Unavailable · no action assumed');setCore('SAFE MODE','Provider unavailable · no action');$('empty').querySelector('h3').textContent='Friday could not finish';$('empty').querySelector('p').textContent=String(error);toast('Run failed safely—no action assumed');}
      finally{clearInterval(stageTimer);button.disabled=false;button.textContent='Run selected demo';}
    }
    async function jsonRequest(path,method='GET',body){
      const options={method,headers:{'Content-Type':'application/json'}};if(body!==undefined)options.body=JSON.stringify(body);
      const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.detail||'Request failed');return data;
    }
    async function loadMandate(){
      try{const data=await jsonRequest('/api/friday/mandate');const m=data.mandate;$('goal').value=m.instruction;$('reserve').value=(m.protected_balance_minor/100).toFixed(2);$('auto-limit').value=(m.automatic_payment_limit_minor/100).toFixed(2);$('auto-execute').checked=m.automatic_sandbox_execution;$('visible-limit').innerHTML='<i>✓</i>'+money(m.automatic_payment_limit_minor);}
      catch(error){toast('Saved instruction unavailable');}
    }
    async function saveMandate(){
      const button=$('save-mandate');button.disabled=true;
      try{const limit=Math.round(Number($('auto-limit').value)*100);await jsonRequest('/api/friday/mandate','PUT',{instruction:$('goal').value,protected_balance_minor:Math.round(Number($('reserve').value)*100),automatic_payment_limit_minor:limit,max_fee_minor:0,automatic_sandbox_execution:$('auto-execute').checked});$('visible-limit').innerHTML='<i>✓</i>'+money(limit);toast('Friday instruction saved');}
      catch(error){toast(String(error));}finally{button.disabled=false;}
    }
    async function publishBill(){
      const button=$('publish-bill');button.disabled=true;
      try{await jsonRequest('/api/friday/test-provider/bills','POST',{bill_reference:$('provider-reference').value.trim(),provider_name:'TN Power',provider_id:'tn-power-test',payee_id:$('provider-payee').value.trim(),amount_minor:Math.round(Number($('provider-amount').value)*100),due_date:new Date(Date.now()+3*86400000).toISOString().slice(0,10),currency:'INR'});$('live-mode').textContent='Provider ready';$('live-result').textContent='The enrolled test provider published a fresh bill. Friday can now verify a message against it.';toast('Fresh test bill published');}
      catch(error){$('live-result').textContent=String(error);}finally{button.disabled=false;}
    }
    function showLiveResult(data){
      $('live-mode').textContent=nice(data.state);$('live-result').replaceChildren();$('live-result').append(node('b',data.message));
      const facts=data.interpretation||{};$('live-result').append(node('p',`Extracted: ${facts.bill_reference||'no reference'} · ${facts.amount_minor?money(facts.amount_minor):'amount unknown'} · ${facts.claimed_payee_id||'payee not stated'}`));
      if(data.reason?.length)$('live-result').append(node('p','Stopped because: '+data.reason.map(nice).join(' · ')));
      resetStages();stage('understand','done','Message structured');stage('ground',data.state==='ATTENTION'?'blocked':'done',data.state==='ATTENTION'?'Needs attention':'Provider record matched');
      if(data.state==='ATTENTION'){stage('plan','skipped','No unsafe plan requested');stage('prove','done','Stopped before action');stage('act','blocked','No money moved');setCore('THREAT CONTAINED','Signal contradicted trusted evidence');}
      else if(data.state==='READY'){stage('plan','active','Ready for your approval');setCore('EVIDENCE LOCKED','Ready for bounded execution');}
      if(data.state==='READY'){const action=node('button','Approve this artificial-money task','planner');action.type='button';action.addEventListener('click',async()=>{action.disabled=true;try{const completed=await jsonRequest('/api/friday/live-input/'+encodeURIComponent(data.event_id)+'/run','POST');showLiveResult(completed.signal);render(completed.run);}catch(error){$('live-result').append(node('p',String(error)));}});$('live-result').append(action);}
      if(data.run_id)$('live-result').append(node('p','Run '+data.run_id+' · '+(data.money_moved?'one artificial-money payment recorded':'no new payment recorded')));
    }
    async function checkLive(){
      const button=$('check-live');button.disabled=true;button.textContent='Friday is analysing…';setCore('ANALYSING SIGNAL','Extracting financial intent');$('live-mode').textContent='Understanding';resetStages();pulse('understand','Extracting the financial request');
      try{const data=await jsonRequest('/api/friday/live-input','POST',{source_type:liveSource,content_text:$('live-input').value});showLiveResult(data);toast(data.state==='ATTENTION'?'Friday stopped for attention':'Live input checked');liveSource='MESSAGE';}
      catch(error){$('live-mode').textContent='Unavailable';$('live-result').textContent=String(error);stage('understand','blocked','Could not interpret safely');setCore('SAFE MODE','Signal could not be verified');}finally{button.disabled=false;button.textContent='Handle this safely';}
    }
    function startVoice(){
      const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){$('live-result').textContent='Voice recognition is unavailable in this browser. Type the same request instead.';return;}
      const recognition=new SpeechRecognition();recognition.lang='en-IN';recognition.interimResults=false;$('speak-live').disabled=true;$('speak-live').textContent='Listening…';
      recognition.onresult=event=>{liveSource='VOICE_TRANSCRIPT';$('live-input').value=event.results[0][0].transcript;$('live-result').textContent='Voice captured. Friday will use this transcript as the new input.';};
      recognition.onerror=event=>{$('live-result').textContent='Voice capture failed: '+event.error;};recognition.onend=()=>{$('speak-live').disabled=false;$('speak-live').textContent='◉ Speak';};recognition.start();
    }
    async function init(){
      try{const response=await fetch('/api/friday/scenarios');const data=await response.json();if(!response.ok)throw new Error(data.detail||'API unavailable');catalogue=data.scenarios;$('ai-status').textContent=data.configured_mode==='LOCAL_RULES'?'Local baseline ready':data.model+' ready';
        data.scenarios.forEach(item=>{const [icon,title]=labels[item.id]||['·',item.name];const button=node('button',undefined,'scenario');button.type='button';button.dataset.id=item.id;button.setAttribute('aria-pressed','false');button.append(node('span',icon,'scenario-icon'));const copy=node('span');copy.append(node('b',title),node('small',item.description));button.append(copy);button.addEventListener('click',()=>selectScenario(item.id));$('scenarios').append(button);});selectScenario(selected);
        if(location.hash.startsWith('#run=')){const response=await fetch('/api/friday/runs/'+encodeURIComponent(decodeURIComponent(location.hash.slice(5))));if(response.ok)render(await response.json());}
        await loadMandate();
      }catch(error){$('ai-status').textContent='API unavailable';$('run').disabled=true;$('scenario-copy').textContent=String(error);}
    }
    let watching=false;
    async function inboxRequest(path='/api/friday/inbox',body){
      const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
      if(!response.ok)throw new Error('Inbox unavailable. Monitoring status could not be checked.');
      return response.json();
    }
    function showInbox(data){
      watching=data.enabled;$('watch-status').textContent=watching?'Monitoring enabled':'Paused';
      $('watch-toggle').textContent=watching?'Pause monitoring':'Enable bill monitoring';$('watch-toggle').disabled=false;
      $('bill-inbox').replaceChildren();
      data.items.forEach(item=>{const li=node('li');li.append(node('b',nice(item.case_id.replaceAll('-','_'))+' · '+nice(item.state)),node('small',item.result.message||'Waiting for the background worker.'));
        li.append(node('p','Sample due date: '+new Date(item.due_at).toLocaleDateString()+(item.reminder_due?' · Reminder: due within two days':'')));
        if(item.result.mode)li.append(node('small','Checked using '+item.result.mode+' · '+item.result.model));
        if(item.state==='UNAVAILABLE'){const retry=node('button','Retry check','planner');retry.type='button';retry.addEventListener('click',async()=>{retry.disabled=true;try{showInbox(await inboxRequest('/api/friday/inbox/'+encodeURIComponent(item.event_id)+'/retry',{}));}catch(e){$('inbox-error').textContent=e.message;retry.disabled=false;}});li.append(retry);}
        $('bill-inbox').append(li);
      });
      if(!data.items.length)$('bill-inbox').append(node('li','No bills received yet. Use “Deliver selected sample bill” to simulate a provider event.'));
      $('inbox-error').textContent='';
    }
    async function refreshInbox(){try{showInbox(await inboxRequest());}catch(e){$('inbox-error').textContent=e.message;$('watch-status').textContent='Status unavailable';}}
    $('watch-toggle').addEventListener('click',async()=>{try{showInbox(await inboxRequest('/api/friday/watch',{enabled:!watching}));}catch(e){$('inbox-error').textContent=e.message;}});
    $('deliver-bill').addEventListener('click',async()=>{try{showInbox(await inboxRequest('/api/friday/arrivals/'+encodeURIComponent(selected),{}));}catch(e){$('inbox-error').textContent=e.message;}});
    $('save-mandate').addEventListener('click',saveMandate);$('publish-bill').addEventListener('click',publishBill);$('check-live').addEventListener('click',checkLive);$('speak-live').addEventListener('click',startVoice);
    setInterval(refreshInbox,5000);refreshInbox();
    $('run').addEventListener('click',run);init();
  </script>
</body>
</html>"""
