"""Multi-screen presentation over Friday's existing, authenticated API controls.

No financial permission, execution gate, or backend credential lives here.
Hash routes work through both the local server and the private cloud gateway.
"""

EXPERIENCE_CSS = r"""
<style id="friday-experience-styles">
  body{background:#060b13;background-image:radial-gradient(ellipse at 50% 8%,#10283c 0,transparent 55%);color:#eef6ff}
  .topbar{position:relative;background:rgba(6,11,19,.92);border-bottom:1px solid #203242}
  .shell.layout{display:block;max-width:1120px;padding:28px 0 48px}.sidebar{display:none!important}
  .workspace{border:0;background:none;box-shadow:none;overflow:visible}.workspace>.body{display:none!important}
  .friday-nav{display:flex;align-items:center;justify-content:center;gap:6px;padding:16px 12px;border-bottom:1px solid #172635;flex-wrap:wrap}
  .friday-nav button,.screen-back{border:1px solid transparent;background:transparent;color:#a7bbce;min-height:44px;padding:10px 18px;border-radius:24px;font:600 13px inherit;cursor:pointer}
  .friday-nav button:hover,.screen-back:hover{background:#142536;color:white}.friday-nav button[aria-current="page"]{background:#16394c;border-color:#327188;color:#c9f8ff}
  button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,summary:focus-visible{outline:3px solid #9cecff!important;outline-offset:4px}
  .friday-view[hidden]{display:none!important}.friday-view{animation:screen-arrive .28s ease-out;min-width:0}
  @keyframes screen-arrive{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}
  .screen-heading{max-width:760px;margin:4px auto 28px}.screen-heading .eyebrow{color:#8dccdf;letter-spacing:.17em;font-size:11px}
  .screen-heading h1{font-size:clamp(30px,4vw,46px);line-height:1.1;letter-spacing:-.035em;margin:12px 0;color:#f0f8ff}
  .screen-heading p{font-size:15px;line-height:1.65;color:#a0b8cc;max-width:660px}.screen-back{padding-left:0;margin-bottom:8px}
  .friday-view .card,.friday-view .mission-details,.friday-view .assurance-board{border-radius:22px;border:1px solid #294152;background:linear-gradient(145deg,rgba(19,36,53,.94),rgba(8,18,29,.97));box-shadow:0 14px 50px #0003;clip-path:none}
  .friday-view .card{padding:28px}.friday-view .card-head{gap:12px;flex-wrap:wrap}.friday-view .run,.friday-view .planner{border-radius:14px;min-height:48px;padding:13px 22px;font-size:14px;clip-path:none}
  .friday-view .run{background:#9ce8f8;color:#06202d;border-color:#9ce8f8;box-shadow:0 5px 24px #4cceeb20}.friday-view .run:hover{background:#c0f5ff;transform:translateY(-1px)}
  .friday-view .planner{background:#13283a;color:#d6e9fa;border:1px solid #36556b}.friday-view .field,.friday-view textarea{background:#07131f;color:#e6f4ff;border:1px solid #38566c;border-radius:14px;font-size:15px;line-height:1.6;padding:16px}
  .friday-view .label{font-size:12px;color:#c3d4e3;letter-spacing:.03em}.friday-view label{color:#c3d4e3;font-size:13px}
  .friday-view[data-screen="home"] .hero{display:flex;flex-direction:column-reverse;align-items:center;text-align:center;border:0;background:none;padding:0 20px 22px;gap:6px}
  .friday-view[data-screen="home"] .hero:before,.friday-view[data-screen="home"] .hero:after{display:none}
  .friday-view[data-screen="home"] .hero-main{max-width:820px}.friday-view[data-screen="home"] .hero h2{font-size:clamp(35px,5.5vw,62px);line-height:1.08;letter-spacing:-.045em;text-align:center;margin:12px 0}
  .friday-view[data-screen="home"] .hero p{font-size:16px;line-height:1.6;color:#a4bdcf;max-width:660px;margin:18px auto 0}
  .friday-view[data-screen="home"] .core-console{height:200px;transform:scale(.8);margin:-18px 0 -12px}.friday-view[data-screen="home"] .system-line{display:none}
  .home-command{max-width:760px;margin:12px auto 26px;padding:12px;display:flex;gap:12px;border:1px solid #355769;border-radius:22px;background:#0c1b29;box-shadow:0 8px 40px #5ee1ff09}
  .home-command input{flex:1;min-width:0;background:transparent;border:0;color:#ebf7ff;padding:10px 14px;font-size:15px}.home-command input::placeholder{color:#87a4ba}
  .task-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;max-width:1000px;margin:0 auto}
  .task-tile{min-height:165px;text-align:left;border-radius:22px;border:1px solid #294658;background:linear-gradient(145deg,#132b3c,#0b1928);color:#effaff;padding:24px;cursor:pointer;transition:transform .18s,border-color .18s,background .18s;position:relative}
  .task-tile:hover{transform:translateY(-5px);border-color:#83d9ef;background:linear-gradient(145deg,#1a3c50,#102337)}
  .task-tile .tile-label{display:block;font-size:10px;color:#8fc5db;text-transform:uppercase;letter-spacing:.14em;margin-bottom:20px}.task-tile b{display:block;font-size:18px;margin-bottom:9px;letter-spacing:-.015em}.task-tile small{display:block;font-size:12px;color:#afc5d7;line-height:1.6}
  .screen-note{max-width:760px;margin:24px auto;color:#92aabd;font-size:12px;line-height:1.7;text-align:center}
  .task-form{max-width:760px;margin:auto}.live-card{margin:0!important}.command-prompt{display:block}.command-avatar{display:none}.command-input{min-height:150px}.command-copy h3{font-size:23px}.command-copy p{font-size:14px;line-height:1.7;color:#a6bece}
  .provider-setup{margin-top:25px;padding:20px;border-radius:15px;background:#091723;border-color:#31495c}.provider-setup summary{font-size:11px;line-height:1.6}.form-grid{gap:15px}
  .customer-examples{margin-top:22px;padding:20px;border:1px solid #34546a;border-radius:16px;background:#0d2130}.customer-examples h4{margin:0 0 8px;font-size:17px}.customer-examples p{margin:0 0 14px;color:#abc4d5;font-size:12px;line-height:1.6}.customer-examples .inline-actions{display:flex;flex-wrap:wrap;gap:10px}
  .household-inbox{max-width:1000px;margin:20px auto 0;padding:22px;border:1px solid #294658;border-radius:22px;background:#0d1e2c}.household-inbox h2{margin:0 0 6px;font-size:20px}.household-inbox p{margin:0 0 14px;color:#abc4d5;font-size:12px;line-height:1.6}.household-bill-list{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.household-bill{min-height:105px;padding:15px;border:1px solid #36566a;border-radius:14px;background:#11283a;color:#e7f6ff;text-align:left;cursor:pointer}.household-bill b,.household-bill span,.household-bill small{display:block}.household-bill b{font-size:14px}.household-bill span{margin:8px 0;font-size:18px;font-weight:700}.household-bill small{font-size:11px;color:#afc8d9;line-height:1.5}@media(max-width:800px){.household-bill-list{grid-template-columns:1fr}}
  .upload-row{display:flex;flex-direction:column;align-items:stretch;gap:18px;border:0;margin:0;padding:10px 0}.upload-row input{padding:30px 18px;border:1px dashed #527e96;border-radius:18px;background:#0a1b29;font-size:14px;width:100%}.upload-note{font-size:12px;color:#a2baca}.upload-row .planner{align-self:flex-start}
  .demo-layout{display:grid;grid-template-columns:1.15fr 1fr;gap:24px}.demo-layout .scenario-list{gap:12px;grid-template-columns:1fr}.demo-layout .scenario{min-height:80px;padding:17px;border-radius:16px;border:1px solid #28475a;background:#0b1d2d}.scenario b{font-size:15px}.scenario small{font-size:12px;line-height:1.5;color:#a7becd}.scenario[aria-pressed="true"]{border-color:#84dbed;background:#153647}
  .demo-controls{padding:28px;border-radius:22px;border:1px solid #2c4e62;background:#102536;align-self:start;position:sticky;top:20px}.demo-controls h2{font-size:23px}.demo-controls p{color:#b2c9db;font-size:14px;line-height:1.7}.demo-controls .run-controls{display:grid;position:static;width:100%;gap:14px;grid-template-columns:1fr}.scope{font-size:12px;color:#abc3d5}
  .run-heading{max-width:none;display:block;position:relative;padding-right:240px}.run-heading h1{font-size:36px}.run-signal{position:absolute;right:0;top:55px;border:1px solid #3b6278;border-radius:30px;padding:10px 18px;font-size:12px;color:#b8eaff;white-space:nowrap}
  [data-screen="run"][data-state="working"] .run-signal{animation:status-breathe 1.4s ease-in-out infinite}
  @keyframes status-breathe{50%{box-shadow:0 0 22px #52d8fa35;border-color:#9cecff}}
  [data-screen="run"][data-state="complete"] .run-signal{color:#9df1c9;border-color:#397d65;background:#0f2b25}
  [data-screen="run"][data-state="held"] .run-signal{color:#ffc3ca;border-color:#a34e5b;background:#301b28}
  .run-source{padding:18px 24px;border:1px solid #28495d;border-radius:18px;background:#091d2a;margin-bottom:22px;line-height:1.65;color:#c9ddeb;overflow-wrap:anywhere}.run-source:empty{display:none}.run-source>p{font-size:13px}.run-source blockquote{font-size:12px;border-left:2px solid #7dd7ed;padding-left:12px;color:#a9c6d9}
  .assurance-board{padding:25px!important;margin-bottom:22px}.stage{border-radius:16px;clip-path:none;min-height:120px;padding:18px}.stage b{font-size:14px}.stage em{font-size:11px;color:#bfd3e2;line-height:1.6}.stage.done{border-color:#3c927f;background:linear-gradient(140deg,#133d36,#0c2728)}.stage.blocked{border-color:#b45768;background:linear-gradient(140deg,#3c2030,#261b28)}
  .briefing{border-radius:22px;overflow:hidden;grid-template-columns:1.1fr 1fr}.brief-main{padding:24px;background:#102739}.brief-main:after{display:none}.brief-main h3{font-size:25px}.brief-main p{font-size:14px;line-height:1.7}.brief-side{gap:12px}.metric{border-radius:14px;padding:16px}.metric span{font-size:10px}.metric b{font-size:23px}.metric small{font-size:11px}
  .verdict{border-radius:18px;padding:22px;clip-path:none;margin:18px 0}.verdict h3{font-size:20px}.verdict p{font-size:14px;line-height:1.7}.mission-details{padding:22px}.mission-details>summary{font-size:12px}.result-toolbar{flex-wrap:wrap;gap:8px;font-size:11px;color:#9fb5c5}
  .run-actions{display:flex;gap:12px;justify-content:center;margin:28px 0;flex-wrap:wrap}.permission-card{max-width:760px;margin:auto}.permission-card details{border:0;background:none;padding:0}.permission-card summary{font-size:17px;margin-bottom:20px}.promise{max-width:760px;margin:22px auto;grid-template-columns:repeat(3,1fr)}
  .activity-list{display:grid;gap:12px;max-width:860px;margin:auto}.activity-entry{display:flex;gap:18px;align-items:center;text-align:left;color:#e1f4ff;background:#102435;border:1px solid #30516a;border-radius:18px;padding:20px;width:100%;cursor:pointer}.activity-entry:hover{border-color:#92d9ed}.activity-entry b{display:block;font-size:14px}.activity-entry small{display:block;font-size:11px;color:#96b4c9;margin-top:6px}.activity-entry .status{margin-left:auto;font-size:12px;white-space:nowrap}.activity-entry .status.good{color:#92eac7}.activity-entry .status.held{color:#ffafbc}
  .activity-empty{padding:35px;text-align:center;border:1px dashed #355267;border-radius:20px;color:#b8cede}.activity-refresh{display:block;margin:0 auto 24px}.route-announcement{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
  @media(max-width:800px){.task-grid{grid-template-columns:repeat(2,1fr)}.demo-layout{grid-template-columns:1fr}.demo-controls{position:static}.briefing{grid-template-columns:1fr}.friday-nav{gap:0}.friday-nav button{padding:9px 12px;font-size:12px}.shell.layout{padding-top:20px}.pipeline{grid-template-columns:repeat(2,1fr)}}
  @media(max-width:520px){.home-command{flex-direction:column}.task-grid{grid-template-columns:1fr 1fr;gap:10px}.task-tile{min-height:165px;padding:17px}.task-tile b{font-size:16px}.task-tile .tile-label{margin-bottom:13px}.screen-heading h1{font-size:32px}.friday-view .card{padding:20px}.promise{grid-template-columns:1fr}.run-heading{display:block;padding-right:0}.run-signal{position:static;display:inline-block;margin:10px 0}.pipeline{grid-template-columns:1fr}.activity-entry{padding:16px;gap:8px;flex-wrap:wrap}.friday-view[data-screen="home"] .core-console{transform:scale(.7);margin:-28px 0}.topbar .pill.optional{display:none}}
  /* Progressive 3D interaction; no motion ever represents financial evidence. */
  :root{--friday-pass:#7ef4bc;--friday-held:#ff91a6;--friday-review:#ffd28a;--friday-live:#91eaff}
  .task-grid,.pipeline{perspective:1100px}.task-tile{transform-style:preserve-3d;isolation:isolate;overflow:hidden;box-shadow:0 12px 30px #0004,inset 0 1px 0 #d3edff12}
  .task-tile:nth-child(2){background:linear-gradient(145deg,#202d50,#101c30)}.task-tile:nth-child(3){background:linear-gradient(145deg,#133b3b,#102331)}.task-tile:nth-child(4){background:linear-gradient(145deg,#332a4c,#181c30)}
  .task-tile:before{content:'';position:absolute;inset:0;pointer-events:none;z-index:-1;background:radial-gradient(circle at var(--mx,50%) var(--my,20%),#98eaff28,transparent 65%);opacity:.25;transition:opacity .35s}
  .task-tile:hover:before{opacity:1}.task-tile b{transform:translateZ(20px)}.task-tile .tile-label{transform:translateZ(12px)}
  .task-tile[data-tilting]{transform:perspective(900px) rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg)) translateY(-6px);box-shadow:0 24px 50px #0007,0 0 24px #70cfff12,inset 0 1px 0 #d3edff25}
  button,a,summary,input,textarea,select{transition:transform .28s cubic-bezier(.2,.8,.2,1),box-shadow .28s,border-color .28s,background-color .28s,color .2s}
  @media(hover:hover) and (pointer:fine){button:not(:disabled):hover,.friday-view summary:hover{transform:translateY(-3px);box-shadow:0 8px 22px #59ceff16}.task-tile:not(:disabled):hover{transform:perspective(900px) rotateX(var(--rx,0deg)) rotateY(var(--ry,0deg)) translateY(-6px)}.activity-entry:hover{transform:translateX(4px)}.stage:hover{transform:translateY(-4px);box-shadow:0 12px 22px #0004}}
  button:not(:disabled):active{transform:translateY(1px) scale(.985)!important}button:disabled{cursor:wait;transform:none!important}
  input:focus,textarea:focus,select:focus{border-color:#91eaff!important;box-shadow:0 0 0 4px #7fdfff12}.friday-view .card:hover{border-color:#486477}
  .friday-view{animation:screen-arrive .45s cubic-bezier(.2,.8,.2,1)}.task-tile,.stage,.metric{transition:transform .3s cubic-bezier(.2,.8,.2,1),box-shadow .3s,border-color .3s,background .3s}
  .stage{position:relative;overflow:hidden;box-shadow:inset 0 1px 0 #ffffff10}.stage.active{border-color:var(--friday-live);box-shadow:0 0 22px #71d9ff24}.stage.active:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(100deg,transparent,#91eaff15,transparent);transform:translateX(-100%);animation:evidence-shimmer 2s linear infinite}
  @keyframes evidence-shimmer{to{transform:translateX(100%)}}
  .stage.done{border-color:#53be91;background:linear-gradient(145deg,#16483b,#102b30)}.stage.blocked{border-color:#df7189;background:linear-gradient(145deg,#512737,#291d30)}.stage.skipped{border-style:dashed;opacity:.75}
  [data-state="complete"] .brief-main,[data-state="complete"] .verdict{border:1px solid #4bc38d;background:linear-gradient(135deg,#163d32,#132637);box-shadow:0 0 30px #6ff4b80b}
  [data-state="held"] .brief-main,[data-state="held"] .verdict{border:1px solid #d86f86;background:linear-gradient(135deg,#472538,#221f32);box-shadow:0 0 30px #ff91a60b}
  [data-state="attention"] .run-signal{color:var(--friday-review);border-color:#b68b4a;background:#30271c}
  [data-state="attention"] .run-source{border-color:#b68b4a;background:linear-gradient(140deg,#2c271d,#142633)}
  .outcome-key{display:flex;gap:18px;flex-wrap:wrap;color:#b3c6d6;font-size:11px;margin:20px 0}.outcome-key span:before{content:'';display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:7px;background:var(--friday-live)}.outcome-key .pass:before{background:var(--friday-pass)}.outcome-key .held:before{background:var(--friday-held)}.outcome-key .review:before{background:var(--friday-review)}
  .activity-entry[data-outcome="good"]{border-left:3px solid #7ef4bc;background:linear-gradient(100deg,#12362e,#142336 65%)}.activity-entry[data-outcome="held"]{border-left:3px solid #ff91a6;background:linear-gradient(100deg,#382332,#142336 65%)}.activity-entry[data-outcome="review"]{border-left:3px solid #ffd28a}.activity-entry .status{border-radius:24px;padding:7px 12px;background:#091521;white-space:normal}.activity-entry .status.review{color:var(--friday-review)}
  .motion-toggle{font-size:11px!important;border-color:#345063!important;margin-left:12px;color:#9ddced!important}.home-command:focus-within{border-color:#91eaff;box-shadow:0 0 0 4px #7fdfff0b,0 14px 60px #5ee1ff12}
  html[data-motion="off"] *,html[data-motion="off"] *:before,html[data-motion="off"] *:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}html[data-motion="off"] .task-tile,html[data-motion="off"] button,html[data-motion="off"] .stage{transform:none!important}
  /* Command centre: a reused core, real journal briefing and progressive help. */
  .friday-view[data-screen="home"] .hero{display:grid;grid-template-columns:1.3fr .7fr;grid-template-rows:1fr;text-align:left;padding:24px 30px;gap:24px;min-height:340px;border:1px solid #244759;border-radius:28px;background:linear-gradient(110deg,#0c1d2dbb,#0d273b55);box-shadow:inset 0 1px 0 #9cecff16,0 28px 60px #0003}
  .friday-view[data-screen="home"] .hero h2{text-align:left;font-size:clamp(36px,4.6vw,56px);margin:16px 0}.friday-view[data-screen="home"] .hero p{margin:18px 0 0;font-size:15px}.friday-view[data-screen="home"] .core-console{height:290px;transform:none;margin:0;perspective:800px}
  .friday-view[data-screen="home"] .core-ring.r1{width:240px;height:240px}.friday-view[data-screen="home"] .core-ring.r2{width:195px;height:195px}.friday-view[data-screen="home"] .core-ring.r3{width:145px;height:145px}.friday-view[data-screen="home"] .core-center{width:92px;height:92px}.friday-view[data-screen="home"] .core-center span{font-size:13px}.friday-view[data-screen="home"] .core-state{bottom:0;width:100%}.core-state small{display:block;margin-top:6px}
  .cockpit-tools{display:flex;gap:10px;align-items:center;margin:0 0 18px;color:#9dc4da;font-size:11px;letter-spacing:.07em}.cockpit-tools button{margin-left:auto;padding:9px 15px;border:1px solid #395a6e;background:#102334;color:#d3eaff;border-radius:18px;min-height:44px;cursor:pointer;font:inherit}
  .command-hints{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin:-12px 0 26px}.command-hints button{border:1px solid #294e62;border-radius:18px;background:#112435;color:#afdeed;padding:9px 14px;min-height:44px;cursor:pointer;font-size:12px}.command-hints kbd{color:#b4d8ea;padding:4px 8px;border:1px solid #406479;border-radius:6px;font-size:11px}
  .cockpit-brief{margin:26px auto 0;border:1px solid #2b4b60;border-radius:22px;padding:23px;background:linear-gradient(130deg,#112d39,#141e31)}.cockpit-brief h2{font-size:19px;margin:0 0 8px}.cockpit-brief p{font-size:13px;line-height:1.7;color:#bdd0dc}.cockpit-brief .brief-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:18px}.brief-stat{padding:15px;border-radius:15px;border:1px solid #375263;background:#08162466}.brief-stat b{display:block;font-size:27px;color:#c2f5ff}.brief-stat small{font-size:11px;color:#aac7d6}.cockpit-brief .brief-time{font-size:10px;color:#91acbe;margin-top:14px}
  .activity-tools{max-width:860px;margin:0 auto 22px;display:flex;align-items:center;gap:10px;flex-wrap:wrap}.activity-tools input{flex:1;min-width:180px;padding:13px 16px;color:#d4efff;background:#0a1b29;border:1px solid #375366;border-radius:14px;min-height:44px}.activity-tools button{border:1px solid #375366;background:#122638;color:#b8d8e8;border-radius:15px;padding:11px 16px;min-height:44px;cursor:pointer}.activity-tools button[aria-pressed="true"]{background:#224756;border-color:#88d6e7;color:#dcf8ff}.activity-entry[hidden]{display:none!important}.activity-count{max-width:860px;margin:0 auto 16px;font-size:12px;color:#adc6d6}.activity-empty[hidden]{display:none}
  .friday-help{max-width:620px;width:calc(100% - 36px);max-height:85vh;overflow:auto;padding:30px;border:1px solid #6ea4b9;border-radius:24px;background:linear-gradient(145deg,#132f41,#0d192a);color:#e5f6ff;box-shadow:0 30px 100px #0009}.friday-help::backdrop{background:#020b16b8;backdrop-filter:blur(7px)}.friday-help h2{font-size:29px;letter-spacing:-.03em;margin:16px 0}.friday-help p{font-size:14px;line-height:1.75;color:#b9d2e2}.friday-help ol{padding-left:22px;line-height:1.7;color:#c1d9e8;font-size:14px}.friday-help li{margin:12px 0}.friday-help button{border:1px solid #507c93;color:#d4f1ff;background:#183447;border-radius:15px;min-height:44px;padding:11px 16px;cursor:pointer}.friday-help .help-close{float:right}.friday-help .help-scope{padding:15px;background:#06142166;border-radius:15px;border:1px solid #354f62}
  @media(max-width:760px){.friday-view[data-screen="home"] .hero{grid-template-columns:1fr;padding:24px 22px;gap:4px}.friday-view[data-screen="home"] .hero-main{order:2;text-align:center}.friday-view[data-screen="home"] .hero h2{text-align:center;font-size:36px}.friday-view[data-screen="home"] .hero p{margin:16px auto}.friday-view[data-screen="home"] .core-console{height:235px;transform:scale(.85);margin:-14px 0}.cockpit-brief .brief-stats{gap:8px}.brief-stat{padding:12px}.brief-stat b{font-size:23px}.cockpit-tools{font-size:10px;letter-spacing:0}}
  @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}.task-tile,button,.stage{transform:none!important}}
  /* Final pilot layout: one primary action, calm surfaces, evidence-led results. */
  :root{--friday-live:#a5eadb;--friday-pass:#94e2b4;--friday-held:#ff97a3;--friday-review:#f6cc82}
  body{background:#0b0f14;background-image:none}.topbar{background:#0b0f14;border-color:#262d36}.topbar .shell{max-width:1380px}
  .shell.layout{max-width:1160px;padding:26px 0 44px}.friday-nav{background:#0e131a;border-color:#262d36;padding:10px;gap:8px}
  .friday-nav button{border-radius:12px;color:#b0bbc7}.friday-nav button[aria-current="page"]{background:#20342f;border-color:#4f8170;color:#d3f5e7}
  .friday-view[data-screen="home"] .hero{grid-template-columns:minmax(0,1fr) 210px;min-height:310px;padding:32px;border-radius:24px;background:linear-gradient(115deg,#17212a,#121920);border-color:#343f49;box-shadow:none;gap:16px}
  .friday-view[data-screen="home"] .hero h2{font-size:clamp(34px,4.1vw,51px);line-height:1.13;font-weight:650;letter-spacing:-.045em}.accent{color:#afe7d8!important;background:none!important;-webkit-text-fill-color:initial!important;text-shadow:none!important}
  .friday-view[data-screen="home"] .hero p{font-size:14px;color:#bec9d4;margin:16px 0;max-width:510px}.friday-view[data-screen="home"] .core-console{height:210px;transform:scale(.75);transform-origin:center;margin:0 -20px}
  .home-command{margin:22px 0 0;padding:7px;border-radius:15px;background:#0b1219;box-shadow:none;gap:6px;border-color:#51616d;max-width:650px}.home-command input{font-size:14px;padding:12px;min-height:48px}.home-command .run{padding:12px 16px;white-space:nowrap}
  .command-hints{display:none}.cockpit-tools{letter-spacing:.04em;margin-bottom:16px}.cockpit-tools button{background:#161f28;border-color:#384451}
  .task-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:20px 0}.task-tile,.task-tile:nth-child(n){min-height:140px;padding:20px;background:#161e27;border:1px solid #34404c;border-radius:18px;box-shadow:none}.task-tile .tile-label{color:#a5c8bf;margin-bottom:14px}.task-tile b{font-size:16px}.task-tile small{color:#b5c2cf;font-size:12px}.task-tile:before{display:none}.task-tile:hover{border-color:#82b7a6;background:#1c2930}.task-tile[data-tilting]{box-shadow:0 14px 28px #0004}
  .cockpit-brief{background:#121a22;border:1px solid #303d49;border-radius:18px;margin-top:20px;padding:20px}.cockpit-brief .brief-stats{margin-top:14px}.brief-stat{background:transparent;border:0;border-left:2px solid #4d766b;border-radius:0;padding:4px 14px}.brief-stat b{font-size:24px;color:#dcf4ec}.cockpit-brief p{margin-bottom:4px;color:#b3c1ce}.screen-note{color:#a8b7c5;font-size:12px}
  .screen-heading{margin-bottom:24px}.screen-heading h1{font-size:clamp(30px,3.5vw,42px)}.screen-heading p{color:#b6c4d2;font-size:14px}.friday-view .card,.demo-controls,.permission-card,.mission-details,.friday-help{background:#141e28;border-color:#344451;box-shadow:none;border-radius:20px}
  .friday-view .run{background:#b5ecdc;color:#0e2820;box-shadow:none}.friday-view .run:hover{background:#d0f9ec}.friday-view .planner{background:#1c2b37;border-color:#485e70}.friday-view .field,.friday-view textarea{background:#0b141d;border-color:#465a6b}.friday-view .command-input{min-height:180px}.live-card .card-head{display:none}.provider-setup{background:#0f1923}
  .outcome-summary{padding:24px 28px;background:#17242f;border:1px solid #486171;border-radius:20px;margin-bottom:20px}.outcome-summary h2{font-size:clamp(24px,3vw,32px);letter-spacing:-.035em;margin:0 0 12px}.outcome-summary p{line-height:1.65;font-size:15px;margin:0 0 12px;color:#d3e1eb}.outcome-summary small{font-size:13px;line-height:1.6;color:#b9cbd8;display:block}
  [data-state="complete"] .outcome-summary{background:#162c25;border-color:#639f80}[data-state="held"] .outcome-summary{background:#301f29;border-color:#a85b6b}[data-state="attention"] .outcome-summary{background:#2a261e;border-color:#a88c54}
  .run-heading{padding-right:0}.run-signal{position:static;display:inline-block;margin:6px 0 0}.outcome-key{display:none}.run-source{background:#111d28;border-color:#3c5466;padding:20px}.run-source button{min-height:48px}.assurance-board{background:#121d27!important;border-color:#334b5d!important}.stage{min-height:110px;border-radius:12px}.briefing{border-radius:16px}.mission-details>summary{font-size:14px;min-height:44px;display:flex;align-items:center}
  @media(min-width:1250px){.friday-nav{position:fixed;left:20px;top:98px;width:185px;bottom:24px;flex-direction:column;justify-content:flex-start;align-items:stretch;border:1px solid #303d49;border-radius:20px;padding:14px;z-index:10}.friday-nav button{text-align:left}.friday-nav .motion-toggle{margin: auto 0 0;text-align:center}.shell.layout{width:calc(100% - 270px);margin-left:235px;margin-right:35px;max-width:none}.topbar .shell{width:calc(100% - 48px)}}
  @media(max-width:800px){.task-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.friday-view[data-screen="home"] .hero{grid-template-columns:1fr;padding:26px}.friday-view[data-screen="home"] .hero-main{order:0;text-align:left}.friday-view[data-screen="home"] .hero h2{text-align:left}.friday-view[data-screen="home"] .hero p{margin:14px 0}.friday-view[data-screen="home"] .core-console{display:none}.home-command{max-width:none}.friday-nav{justify-content:flex-start;overflow-x:auto;flex-wrap:nowrap}.friday-nav button{flex-shrink:0}.motion-toggle{margin-left:0!important}}
  @media(max-width:520px){.home-command{flex-direction:column;align-items:stretch}.task-grid{grid-template-columns:1fr}.task-tile,.task-tile:nth-child(n){min-height:104px;padding:17px}.task-tile .tile-label{margin-bottom:9px}.screen-heading h1{font-size:30px}.outcome-summary{padding:20px}.topbar .brand small{font-size:10px}.topbar .pill{font-size:10px;padding:7px}.topbar .shell{gap:10px}.friday-view .card{padding:20px}.cockpit-brief .brief-stats{grid-template-columns:repeat(3,minmax(0,1fr))}.brief-stat{padding:4px 8px}.brief-stat small{font-size:10px}}
  .money-workspace{max-width:1000px;margin:auto}.money-summary,.money-capabilities{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:20px 0}.money-stat,.money-capability{padding:20px;border:1px solid #355363;border-radius:16px;background:#10232e}.money-stat span,.money-stat small{display:block;color:#adc4d0;font-size:12px;line-height:1.6}.money-stat strong{display:block;font-size:26px;margin:8px 0;overflow-wrap:anywhere}.money-capabilities{grid-template-columns:repeat(2,minmax(0,1fr))}.money-capability h2{font-size:18px;margin:0 0 8px}.money-capability p{font-size:13px;color:#bdd0db;line-height:1.7}.money-section{margin:24px 0;padding:22px;border:1px solid #355363;border-radius:18px;background:#0d1e29}.money-section h2{margin:0 0 12px;font-size:20px}.money-section p,.money-section li{font-size:13px;line-height:1.7;color:#bdd0db}.money-feedback{padding:16px;border:1px solid #355363;border-radius:14px;color:#bdd0db;line-height:1.7}.money-feedback[data-state="error"]{border-color:#965161;color:#ffd0d8}.money-shortfall{border-left:3px solid #e8bd70;padding-left:14px;color:#ffe0a0!important}.money-row{display:flex;justify-content:space-between;gap:16px;padding:14px 0;border-bottom:1px solid #29424f;flex-wrap:wrap}.money-row:last-child{border:0}.money-row b,.money-row small{display:block}.money-row small{font-size:12px;color:#adc4d0;line-height:1.7}.money-badge{display:inline-block;font-size:11px;padding:5px 9px;border:1px solid #4c6677;border-radius:20px;color:#d0e1eb}.money-controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.money-controls p{margin:0;font-size:12px;color:#adc4d0}.money-section ul{padding-left:20px}.money-refresh:disabled{opacity:.6;cursor:wait}@media(max-width:680px){.money-summary,.money-capabilities{grid-template-columns:1fr}.money-stat strong{font-size:23px}}
  #follow-bill-reference{display:block;width:100%;box-sizing:border-box;margin:10px 0 14px;padding:14px;background:#10232e;color:#ecf6ff;border:1px solid #4c6677;border-radius:12px}
  .money-section [data-state="ACKNOWLEDGED"],.money-section [data-state="ALREADY_ACKNOWLEDGED"]{color:#8de6cb;border-left:3px solid #51bda0;padding-left:12px}
  .money-section [data-state="HOLD"]{color:#ffbac8;border-left:3px solid #df788e;padding-left:12px}
  .money-section [data-state="UNVERIFIED"],.money-section [data-state="UNAVAILABLE"]{color:#ffe0a0;border-left:3px solid #d8b66b;padding-left:12px}
</style>
"""

EXPERIENCE_NAV = """
<nav class="friday-nav" aria-label="Friday pages">
  <button type="button" data-screen-link="home">Friday</button>
  <button type="button" data-screen-link="money">My money</button>
  <button type="button" data-screen-link="bill">Bills</button>
  <button type="button" data-screen-link="document">Documents</button>
  <button type="button" data-screen-link="activity">Activity</button>
  <button type="button" data-screen-link="demos">Safety lab</button>
  <button type="button" data-screen-link="settings">My rules</button>
  <button type="button" id="motion-toggle" class="motion-toggle" aria-pressed="false">Motion on</button>
</nav>
<p id="route-announcement" class="route-announcement" role="status" aria-live="polite"></p>
"""

EXPERIENCE_JS = r"""
    // One purpose per route; all money actions still use the original backend.
    const experience=(()=>{
      const root=document.querySelector('.workspace');const oldBody=root.querySelector('.body');
      // Fine-pointer perspective is cosmetic, never a stage-completion signal.
      const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');const fine=window.matchMedia('(hover: hover) and (pointer: fine)');let motionPreference='on';
      try{motionPreference=localStorage.getItem('friday-motion')||'on';}catch(e){}
      function syncMotion(){const off=reduced.matches||motionPreference==='off';document.documentElement.dataset.motion=off?'off':'on';$('motion-toggle').textContent=reduced.matches?'Reduced motion':off?'Motion off':'Motion on';$('motion-toggle').setAttribute('aria-pressed',String(off));$('motion-toggle').disabled=reduced.matches;}
      $('motion-toggle').addEventListener('click',()=>{motionPreference=motionPreference==='off'?'on':'off';try{localStorage.setItem('friday-motion',motionPreference);}catch(e){}syncMotion();});reduced.addEventListener('change',syncMotion);syncMotion();
      const sidebar=document.querySelector('.sidebar');const views={};let busy=false;let active='home';let loadedRun=null;
      const titles={home:'Your financial co-pilot',money:'Your money. One clear picture.',bill:'Let’s handle your bill.',document:'Let’s read the details.',demos:'See the safety system work.',run:'Friday is on it.',activity:'Everything Friday handled.',settings:'You’re always in control.'};
      const element=(tag,text,className)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(className)e.className=className;return e;};
      function view(name,subtitle){const s=element('section',null,'friday-view');s.dataset.screen=name;s.hidden=true;s.setAttribute('aria-label',titles[name]);
        if(name!=='home'){const h=element('header',null,'screen-heading');const back=element('button','Back to Friday','screen-back');back.type='button';back.dataset.screenLink='home';h.append(back,element('div','FINANCIAL FRIDAY','eyebrow'));const title=element('h1',titles[name]);title.tabIndex=-1;h.append(title,element('p',subtitle));s.append(h);}root.append(s);views[name]=s;return s;}
      const home=view('home');const hero=root.querySelector('.hero');home.append(hero);
      $('workspace-title').innerHTML='Less financial admin.<br><span class="accent">More peace of mind.</span>';
      $('scenario-copy').textContent='Understand your money, handle permitted bills and protect your decisions. Start with one task; Friday checks the evidence and follows the outcome.';
      const command=element('form',null,'home-command');command.innerHTML='<label class="route-announcement" for="home-command">What should Friday handle?</label><input id="home-command" autocomplete="off" placeholder="Paste a bill request for Friday…"><button class="run" type="submit">Check my bill</button>';hero.querySelector('.hero-main').append(command);
      const permissionNote=element('p','Allowed tasks may complete automatically within your saved sandbox rules. Review My rules to change permission.','permission-note');hero.querySelector('.hero-main').append(permissionNote);
      const cockpitTools=element('div',null,'cockpit-tools');const hour=new Date().getHours();cockpitTools.append(element('span',(hour<12?'GOOD MORNING':hour<17?'GOOD AFTERNOON':'GOOD EVENING')+' · FRIDAY COMMAND CENTRE'));const helpButton=element('button','How Friday works');helpButton.type='button';helpButton.setAttribute('aria-haspopup','dialog');cockpitTools.append(helpButton);home.prepend(cockpitTools);
      const hints=element('div',null,'command-hints');[['bill','Handle a bill'],['document','Read a bill photo'],['activity','Show my receipts']].forEach(([screen,label])=>{const b=element('button',label);b.type='button';b.dataset.screenLink=screen;hints.append(b);});hints.append(element('kbd','/ to type'));home.append(hints);
      const guide=element('dialog',null,'friday-help');guide.setAttribute('aria-labelledby','friday-guide-title');guide.innerHTML='<button type="button" class="help-close">Close</button><div class="eyebrow">MEET YOUR FINANCIAL CO-PILOT</div><h2 id="friday-guide-title">You ask. Friday handles the checks.</h2><p>A calm interface. A strict safety boundary.</p><ol><li><b>Set your limits.</b> My rules stores the artificial-money tasks you allow. Reading a bill never grants permission.</li><li><b>Give Friday the details once.</b> Gemini understands the message or document. A separate provider record must support it.</li><li><b>Follow the outcome.</b> Friday completes an allowed sandbox task, checks an uncertain result, or stops with a reason. No silent repeat payments.</li></ol><p class="help-scope">This is an artificial-money pilot, not a live bank connection. No PIN, OTP or bank password is needed. Native voice and continuous cloud monitoring are not enabled.</p><p>Keyboard: / focuses the command outside text fields. ? opens help. Escape closes help. Receipts live in Activity.</p>';document.body.append(guide);let guideReturn=null;function openGuide(){guideReturn=document.activeElement;guide.showModal();guide.querySelector('button').focus();}helpButton.addEventListener('click',openGuide);guide.querySelector('button').addEventListener('click',()=>guide.close());guide.addEventListener('close',()=>{if(guideReturn?.isConnected)guideReturn.focus();});
      const tiles=element('div',null,'task-grid');[
        ['money','01 / UNDERSTAND','My money','Your sandbox balance, protected reserve, bill commitments and recent outcomes.'],
        ['bill','02 / HANDLE','Handle a bill','Give me the request. I’ll check it and handle the allowed task.'],
        ['demos','03 / PROTECT','Try the safety lab','See recipient checks, permission limits and uncertain-payment recovery.'],
        ['activity','04 / FOLLOW THROUGH','My activity','Review verified outcomes. Biller dispute resolution is not connected yet.']
      ].forEach(([route,label,title,copy])=>{const b=element('button',null,'task-tile');b.type='button';b.dataset.screenLink=route;b.append(element('span',label,'tile-label'),element('b',title),element('small',copy));tiles.append(b);});home.append(tiles,element('p','Artificial-money pilot · No real bank account connected · You set the limits.','screen-note'));
      const billInbox=element('section',null,'household-inbox');billInbox.setAttribute('aria-label','Artificial household bills');const billInboxList=element('div',null,'household-bill-list');billInbox.append(element('h2','Sample household bills'),element('p','Read-only artificial biller records. Select one to prepare a request; selection never submits a payment.'),billInboxList);home.insertBefore(billInbox,home.querySelector('.screen-note'));
      async function refreshHouseholdBills(){billInboxList.replaceChildren(element('p','Loading sample bills…'));try{const data=await jsonRequest('/api/friday/test-provider/bills');const now=new Date();const today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');const upcoming=(data.items||[]).filter(b=>b.due_date>=today).slice(0,3);billInboxList.replaceChildren();if(!upcoming.length){billInboxList.append(element('p','No upcoming sample bills. Open Bills to prepare a household example.'));return;}upcoming.forEach(bill=>{const button=element('button',null,'household-bill');button.type='button';button.append(element('b',bill.provider_name),element('span',money(bill.amount_minor)),element('small','Due '+bill.due_date+' · '+bill.bill_reference));button.addEventListener('click',()=>{$('live-input').value=`Please check this one-time ${bill.provider_name} bill ${bill.bill_reference} for INR ${(bill.amount_minor/100).toFixed(2)}. Payee: ${bill.payee_id}.`;show('bill');$('live-input').focus();});billInboxList.append(button);});}catch(e){billInboxList.replaceChildren(element('p','Sample bills could not be loaded. No payment was submitted.'));}}
      const cockpitBrief=element('article',null,'cockpit-brief');cockpitBrief.setAttribute('aria-label','Recorded activity briefing');const briefingTitle=element('h2','Your sandbox briefing');const briefingCopy=element('p','Loading your actual journal. No task is being submitted.');const briefingStats=element('div',null,'brief-stats');const briefingTime=element('div',null,'brief-time');cockpitBrief.append(briefingTitle,briefingCopy,briefingStats,briefingTime);home.insertBefore(cockpitBrief,home.querySelector('.screen-note'));let briefingBusy=false;
      async function refreshBriefing(){if(briefingBusy)return;briefingBusy=true;try{const data=await jsonRequest('/api/friday/today');const rows=data.recent_runs||[];const complete=rows.filter(r=>completedStatuses.includes(r.status)).length;const held=rows.filter(r=>r.status==='HELD').length;briefingCopy.textContent=rows.length?'Your recent recorded outcomes are ready to review. Reopening evidence never submits another payment.':'No recorded tasks yet. Start with a bill or explore a controlled safety scenario.';briefingStats.replaceChildren();[[rows.length,'Recent runs'],[complete,'Confirmed outcomes'],[held,'Held outcomes']].forEach(([value,label])=>{const box=element('div',null,'brief-stat');box.append(element('b',String(value)),element('small',label));briefingStats.append(box);});briefingTime.textContent='Read-only journal snapshot · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · most recent '+rows.length+' runs';}catch(e){briefingCopy.textContent='Your journal is unavailable right now. No task was submitted. Open Activity to retry the read-only check.';briefingStats.replaceChildren();briefingTime.textContent='No result assumed';}finally{briefingBusy=false;}}
      const moneyView=view('money','A read-only overview of this artificial-money workspace, not all your bank accounts. Viewing or refreshing this page cannot move money.');
      const moneyWorkspace=element('div',null,'money-workspace');const moneyControls=element('div',null,'money-controls');const moneyRefresh=element('button','Refresh my money','planner money-refresh');moneyRefresh.type='button';moneyRefresh.setAttribute('aria-label','Refresh the read-only artificial-money overview');const moneyUpdated=element('p','No snapshot loaded.');moneyControls.append(moneyRefresh,moneyUpdated);const moneyFeedback=element('p',null,'money-feedback');moneyFeedback.setAttribute('role','status');moneyFeedback.setAttribute('aria-live','polite');const moneyContent=element('div');moneyWorkspace.append(moneyControls,moneyFeedback,moneyContent);moneyView.append(moneyWorkspace);let moneyBusy=false;
      function workspaceMoney(value){return Number.isSafeInteger(value)&&value>=0?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(value/100):'Not available';}
      function workspaceLink(route,label){const link=element('button',label,'planner');link.type='button';link.dataset.screenLink=route;return link;}
      function workspaceSection(title){const section=element('section',null,'money-section');section.append(element('h2',title));return section;}
      const statementSection=workspaceSection('Use your actual transaction history');
      statementSection.append(element('p','Upload an INR bank-statement CSV for a read-only cash-flow review. This works without sample billers. It does not connect to your bank or change the sandbox balance.'));
      const statementLabel=element('label','Choose statement CSV');statementLabel.htmlFor='statement-file';const statementFile=element('input');statementFile.id='statement-file';statementFile.type='file';statementFile.accept='.csv,text/csv';
      const statementConsent=element('input');statementConsent.type='checkbox';statementConsent.id='statement-consent';const consentLabel=element('label','I agree to send this CSV to the Friday server for temporary analysis. It is not saved or sent to Gemini.');consentLabel.htmlFor='statement-consent';
      const statementHelp=element('p','Required columns: date, description, debit, credit. Use INR rupees, one positive debit OR credit per row. Dates: YYYY-MM-DD or DD/MM/YYYY. Maximum 1 MB / 5,000 rows. Remove account numbers and personal details first.');
      const statementButton=element('button','Analyze my statement','planner');statementButton.type='button';const statementStatus=element('p','No statement uploaded.');statementStatus.setAttribute('role','status');const statementResults=element('div');statementResults.setAttribute('aria-live','polite');
      statementSection.append(statementLabel,statementFile,statementHelp,statementConsent,consentLabel,statementButton,statementStatus,statementResults);moneyWorkspace.insertBefore(statementSection,moneyControls);
      statementButton.addEventListener('click',async()=>{const file=statementFile.files[0];statementResults.replaceChildren();if(!file||!statementConsent.checked){statementStatus.textContent='Choose a CSV and confirm temporary server processing first.';return;}if(file.size>1024*1024){statementStatus.textContent='Choose a CSV smaller than 1 MB.';return;}statementButton.disabled=true;statementStatus.textContent='Reading your uploaded rows. No payment or AI call is being made.';try{const data=await jsonRequest('/api/friday/statements/analyze','POST',{csv_text:await file.text()});if(data.scope!=='USER_SUPPLIED_STATEMENT'||data.money_moved!==false)throw new Error('Unexpected statement response');statementStatus.textContent='Analysis complete: '+data.transaction_count+' transactions · '+data.period.start+' to '+data.period.end;const stats=element('div',null,'money-summary');[[data.totals.money_in_minor,'Money in'],[data.totals.money_out_minor,'Money out']].forEach(([value,label])=>{const card=element('article',null,'money-stat');card.append(element('span',label),element('strong',workspaceMoney(value)));stats.append(card);});const net=element('article',null,'money-stat');const netValue=data.totals.net_flow_minor;net.append(element('span','Net flow (not your balance)'),element('strong',(netValue<0?'−':'')+workspaceMoney(Math.abs(netValue))));stats.append(net);statementResults.append(stats);const months=workspaceSection('Month-by-month cash flow');data.monthly.forEach(row=>months.append(element('p',row.month+' · In '+workspaceMoney(row.credit_minor)+' · Out '+workspaceMoney(row.debit_minor))));statementResults.append(months);const largest=workspaceSection('Largest outgoing entries');data.largest_outgoing.forEach(row=>{const detail=element('div',null,'money-row');detail.append(element('span',row.date+' · '+row.description),element('b',workspaceMoney(row.debit_minor)));largest.append(detail);});statementResults.append(largest);const repeats=workspaceSection('Entries worth checking');if(!data.repeated_rows.length)repeats.append(element('p','No exact repeated entries found. This is not proof that every transaction is legitimate.'));data.repeated_rows.forEach(row=>repeats.append(element('p',row.count+' matching entries · '+row.date+' · '+row.description+' · '+workspaceMoney(row.debit_minor||row.credit_minor)+'. May be legitimate; all remain included in totals.')));statementResults.append(repeats);data.limits.forEach(line=>statementResults.append(element('p',line,'screen-note')));}catch(e){statementStatus.textContent='Statement was not analyzed: '+e.message+'. No partial totals or successful payment are assumed.';}finally{statementButton.disabled=false;statementFile.value='';statementConsent.checked=false;}});
      const clearStatement=element('button','Clear statement results','planner');clearStatement.type='button';clearStatement.addEventListener('click',()=>{statementResults.replaceChildren();statementStatus.textContent='Results cleared from this page.';statementFile.value='';statementConsent.checked=false;});statementSection.append(clearStatement);
      const personalInbox=workspaceSection('What Friday understood from your inputs');personalInbox.append(element('p','Your own messages and documents, separate from demo biller records. Extracted facts are claims, not authenticated bank evidence.'));
      const inboxRefresh=element('button','Load my input history','planner');inboxRefresh.type='button';const personalRows=element('div');personalRows.setAttribute('aria-live','polite');personalInbox.append(inboxRefresh,workspaceLink('document','Read a new document'),personalRows);moneyWorkspace.insertBefore(personalInbox,moneyControls);
      inboxRefresh.addEventListener('click',async()=>{inboxRefresh.disabled=true;personalRows.replaceChildren(element('p','Loading saved interpretations…'));try{const result=await jsonRequest('/api/friday/live-input');personalRows.replaceChildren();if(!result.items.length)personalRows.append(element('p','No inputs yet. Read your own bill image or PDF; a sample provider is not required to understand it.'));result.items.forEach(item=>{const facts=item.interpretation||{};const card=element('article',null,'money-section');card.append(element('h2',item.document?.filename||facts.provider_name||'Financial input'),element('p',facts.summary||'No interpretation available'),element('p','Extracted amount: '+workspaceMoney(facts.amount_minor)+' · Type: '+(facts.request_kind||'Unknown')),element('p','Reference: '+(facts.bill_reference||'Not extracted')+' · Claimed recipient: '+(facts.claimed_payee_id||'Not extracted')),element('p',item.message||'No action prepared'));if(item.understanding)card.append(element('small','Understanding: '+item.understanding.mode+' · '+item.understanding.model));const quotes=element('details');quotes.append(element('summary','Show extracted source evidence'));(facts.evidence_spans||[]).forEach(span=>quotes.append(element('p',span.field+': “'+span.quote+'”')));card.append(quotes,element('p','Model-extracted document quotations are not independently OCR verified. No bank identity or settlement is established.','screen-note'));personalRows.append(card);});personalRows.append(element('p','Most recent 20 saved inputs; this is not a complete bank statement.'));}catch(e){personalRows.replaceChildren(element('p','Input history is unavailable. No payment was submitted.'));}finally{inboxRefresh.disabled=false;}});
      async function refreshMoney(){if(moneyBusy)return;moneyBusy=true;moneyRefresh.disabled=true;moneyContent.replaceChildren();moneyFeedback.dataset.state='loading';moneyFeedback.textContent='Loading the latest sandbox records. No payment is being submitted.';moneyUpdated.textContent='Refreshing read-only snapshot…';try{const data=await jsonRequest('/api/friday/workspace');if(data.scope!=='ARTIFICIAL_MONEY')throw new Error('Unsupported workspace scope');const summary=element('div',null,'money-summary');summary.setAttribute('aria-label','Sandbox money summary');[[data.balance_minor,'Sandbox balance','Recorded account balance; not a live bank connection.'],[data.protected_balance_minor,'Your protected reserve','Your saved rule, not a separate locked account.'],[data.available_above_reserve_minor,'Above your reserve','Not payment authorization; bill and permission checks still apply.']].forEach(([value,title,copy])=>{const stat=element('article',null,'money-stat');stat.append(element('span',title),element('strong',workspaceMoney(value)),element('small',copy));summary.append(stat);});moneyContent.append(summary);
        const budget=workspaceSection('Plan around your essentials');budget.append(element('p','Potential bill commitments (external status unknown): '+workspaceMoney(data.upcoming_total_minor)),element('p','Suggested bill commitments: '+workspaceMoney(data.budget?.committed_minor)+'. This is a planning total, not money reserved or paid.'));const remaining=data.budget?.remaining_after_bills_minor;if(Number.isSafeInteger(remaining)&&remaining>=0)budget.append(element('p','Estimated above-reserve amount after these bills: '+workspaceMoney(remaining)));else if(Number.isSafeInteger(remaining)&&remaining<0)budget.append(element('p','These bills exceed the amount above your reserve by '+workspaceMoney(-remaining)+'. Friday has not paid them or changed your reserve.','money-shortfall'));else budget.append(element('p','The remaining amount is unavailable. No affordability assumption is made.'));if(Number.isSafeInteger(data.budget?.shortfall_minor)&&data.budget.shortfall_minor>0&&!(Number.isSafeInteger(remaining)&&remaining<0))budget.append(element('p','Reported shortfall: '+workspaceMoney(data.budget.shortfall_minor)+'. Review your bills and rules before any payment.','money-shortfall'));budget.append(workspaceLink('settings','Review my rules'));moneyContent.append(budget);
        const bills=workspaceSection('Bill records');bills.append(element('p','Provider records in this sandbox. Reviewing a record never submits a payment.'));const billRows=Array.isArray(data.bills)?data.bills:[];if(!billRows.length)bills.append(element('p','No bill records are available in this snapshot.'));const billStatusLabels={UNPAID_RECORD:'No matching internal receipt',RECORDED_PAID:'Internal artificial-payment receipt matched',RECEIPT_CONFLICT:'Receipt needs reconciliation',REVIEW_INCREASE:'Bill increase needs review'};billRows.forEach(record=>{const row=element('div',null,'money-row');const detail=element('div');detail.append(element('b',record.provider_name||'Provider not supplied'),element('small',(record.bill_reference||'Reference unavailable')+' · Due '+(record.due_date||'date unavailable')),element('small','Recipient: '+(record.payee_id||'not supplied')+' · Status: '+(billStatusLabels[record.status]||record.status||'not supplied')));if(typeof record.reason==='string'&&record.reason)detail.append(element('small',record.reason));if(record.history_status==='NOT_AVAILABLE')detail.append(element('small','Historical comparison unavailable'));const amount=element('div');amount.append(element('b',workspaceMoney(record.amount_minor)));if(record.history_status!=='NOT_AVAILABLE'&&Number.isSafeInteger(record.previous_amount_minor)&&record.previous_amount_minor>=0)amount.append(element('small','Previous amount: '+workspaceMoney(record.previous_amount_minor)));row.append(detail,amount);bills.append(row);});const coverage=data.coverage||{};bills.append(element('p',coverage.may_be_truncated?'Limited snapshot: more bill records may exist. Totals describe only the records returned, not every obligation.':'Snapshot covers only records available from the connected sandbox provider, not all household obligations.'));moneyContent.append(bills);
        const capabilities=element('div',null,'money-capabilities');capabilities.setAttribute('aria-label','Friday capability coverage');const definitions=[['Understand','Balance, bills and receipts in one place.','document','Read a bill document'],['Handle','Submit an eligible artificial-money bill only within your saved permission.','bill','Handle a bill'],['Protect','Check provider, amount, recipient, reserve and replay safeguards.','demos','Explore safety checks'],['Resolve','Kernel tested · connector pending. End-to-end biller dispute resolution is not live.','activity','Review existing outcomes']];definitions.forEach(([title,copy,route,label])=>{const card=element('article',null,'money-capability');card.append(element('h2',title),element('p',copy),workspaceLink(route,label));capabilities.append(card);});moneyContent.append(capabilities);
        const coverageSection=workspaceSection('What is connected now');const capabilityRows=Array.isArray(data.capabilities)?data.capabilities:[];if(!capabilityRows.length)coverageSection.append(element('p','No capability details returned. Do not assume additional integrations are enabled.'));capabilityRows.forEach(item=>{const row=element('div',null,'money-row');const detail=element('div');detail.append(element('b',item.title||item.id||'Capability'),element('small',item.description||'No details supplied'));row.append(detail,element('span',item.status||'Unknown','money-badge'));coverageSection.append(row);});moneyContent.append(coverageSection);
        const recent=workspaceSection('Recent recorded outcomes');const runRows=Array.isArray(data.recent_runs)?data.recent_runs:[];if(!runRows.length)recent.append(element('p','No recorded outcomes yet.'));runRows.forEach(record=>{const row=element('div',null,'money-row');row.append(element('div',(record.case_id||'Task')+' · '+(record.status||'Unknown outcome')));if(typeof record.run_id==='string'&&record.run_id){const open=element('button','Review receipt','planner');open.type='button';open.dataset.runId=record.run_id;row.append(open);}recent.append(row);});moneyContent.append(recent);
        const limits=workspaceSection('Know the boundaries');const limitsList=element('ul');limitsList.append(element('li','Only artificial funds are connected. No bank login, PIN or OTP is requested.'));(Array.isArray(data.limits)?data.limits:[]).filter(item=>typeof item==='string').forEach(item=>limitsList.append(element('li',item)));limits.append(limitsList);moneyContent.append(limits);moneyFeedback.dataset.state='ready';moneyFeedback.textContent='Sandbox snapshot loaded. No financial action was performed.';moneyUpdated.textContent='Loaded '+new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})+' · refresh to retrieve a new snapshot';}catch(e){moneyContent.replaceChildren();moneyFeedback.dataset.state='error';moneyFeedback.textContent='Your money overview could not be loaded. No balance or successful action is assumed. Retry the read-only refresh.';moneyUpdated.textContent='No usable snapshot loaded.';}finally{moneyBusy=false;moneyRefresh.disabled=false;}}
      moneyRefresh.addEventListener('click',refreshMoney);
      const followSection=workspaceSection('Follow through without paying again');
      followSection.append(element('p','Local sandbox only. Friday can acknowledge a bill against its signed artificial-payment receipt. This changes only a local acknowledgement record, never your balance, and does not prove real settlement.'));
      const followLabel=element('label','Bill reference');followLabel.htmlFor='follow-bill-reference';const followReference=element('input');followReference.id='follow-bill-reference';followReference.maxLength=120;followReference.placeholder='Enter a recorded bill reference';
      const followButton=element('button','Match recorded payment','planner');followButton.type='button';const followStatus=element('p','No acknowledgement requested.');followStatus.setAttribute('role','status');followStatus.setAttribute('aria-live','polite');followSection.append(followLabel,followReference,followButton,followStatus);moneyWorkspace.append(followSection);
      followButton.addEventListener('click',async()=>{const reference=followReference.value.trim();if(!reference){followStatus.textContent='Enter a bill reference first.';return;}followButton.disabled=true;followStatus.textContent='Checking the current signed receipt. No payment is being sent.';try{const result=await jsonRequest('/api/friday/follow-through','POST',{bill_reference:reference});const messages={ACKNOWLEDGED:'Local bill acknowledged against its signed artificial-payment receipt. No new debit.',ALREADY_ACKNOWLEDGED:'Already acknowledged. No duplicate acknowledgement or debit.',UNVERIFIED:'No matching payment can be established. Friday did not mark the bill paid.',HOLD:'Evidence conflict. Friday changed nothing; do not blindly repay.',UNAVAILABLE:'This local acknowledgement connector is not enabled on Cloud Run.'};followStatus.textContent=messages[result.state]||'Unknown result. No successful acknowledgement is assumed.';followStatus.dataset.state=result.state;}catch(e){followStatus.textContent='Acknowledgement outcome unavailable. Recheck the same reference; do not submit another payment.';}finally{followButton.disabled=false;}});
      tiles.querySelectorAll('.task-tile').forEach(tile=>{tile.addEventListener('pointermove',e=>{if(!fine.matches||document.documentElement.dataset.motion==='off')return;const r=tile.getBoundingClientRect();const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));const y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));tile.style.setProperty('--rx',((.5-y)*7).toFixed(2)+'deg');tile.style.setProperty('--ry',((x-.5)*9).toFixed(2)+'deg');tile.style.setProperty('--mx',(x*100)+'%');tile.style.setProperty('--my',(y*100)+'%');tile.dataset.tilting='true';});tile.addEventListener('pointerleave',()=>{delete tile.dataset.tilting;tile.style.setProperty('--rx','0deg');tile.style.setProperty('--ry','0deg');});});
      const bill=view('bill','Paste the bill request once. Friday checks the provider record and your saved permission before taking any action.');
      const live=root.querySelector('.live-card');live.classList.add('task-form');const upload=live.querySelector('.upload-row');const source=$('live-result');bill.append(live);
      $('live-input').value='';$('live-mode').textContent='Ready for a request';$('live-input').placeholder='Include the bill reference, amount and recipient. Example: TN Power invoice BILL-123, INR 2487.00, payee tnpower@upi.';
      live.querySelector('h3').textContent='What should I handle?';live.querySelector('.command-copy p').textContent='Use the actual bill details. I won’t treat a message as permission to ignore your rules.';
      const doc=view('document','Choose a bill photo or PDF. Gemini extracts the facts; Friday checks them against the enrolled provider before a task can proceed.');const docCard=element('article',null,'card task-form');docCard.append(element('h2','One document. The important details.'),upload);doc.append(docCard,element('p','Raw uploads are discarded after analysis. Do not upload PINs, OTPs, credentials or identity documents.','screen-note'));
      const demos=view('demos','Controlled artificial-money scenarios, not real bank incidents. Choose one situation, then follow its dedicated run.');const demoLayout=element('div',null,'demo-layout');demoLayout.append($('scenarios'));const controls=element('article',null,'demo-controls');controls.append(element('h2','Choose a situation.'));const description=element('p',null);description.id='demo-description';controls.append(description,sidebar.querySelector('.sidebar-run'));demoLayout.append(controls);demos.append(demoLayout);
      const settings=view('settings','Friday can complete only tasks inside this saved permission. Changing the interface never changes your financial rules.');const permission=element('article',null,'card permission-card');const details=sidebar.querySelector('details');details.open=true;permission.append(details);settings.append(permission,root.querySelector('.promise'));
      const activity=view('activity','Reopen an actual recorded run. These are your sandbox outcomes—not a live connection to your personal bank.');const refresh=element('button','Refresh activity','planner activity-refresh');refresh.type='button';refresh.id='refresh-activity';const list=element('div',null,'activity-list');list.id='friday-activity';activity.append(refresh,list);
      const activityTools=element('div',null,'activity-tools');const search=element('input');search.type='search';search.placeholder='Find a task or run…';search.setAttribute('aria-label','Search recorded activity');activityTools.append(search);let activityFilter='all';const filterButtons=[];[['all','All'],['good','Confirmed'],['held','Held'],['review','Review']].forEach(([key,label])=>{const b=element('button',label);b.type='button';b.dataset.filter=key;b.setAttribute('aria-pressed',String(key==='all'));b.addEventListener('click',()=>{activityFilter=key;filterButtons.forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.filter===key)));filterActivity();});filterButtons.push(b);activityTools.append(b);});const activityCount=element('p',null,'activity-count');activityCount.setAttribute('role','status');const noMatches=element('p','No matching outcomes. Try another filter or search.','activity-empty');noMatches.hidden=true;activity.insertBefore(activityTools,list);activity.insertBefore(activityCount,list);activity.append(noMatches);search.addEventListener('input',filterActivity);function filterActivity(){const entries=Array.from(list.querySelectorAll('.activity-entry'));const query=search.value.trim().toLowerCase();let visible=0;entries.forEach(b=>{b.hidden=(activityFilter!=='all'&&b.dataset.outcome!==activityFilter)||!b.textContent.toLowerCase().includes(query);if(!b.hidden)visible++;});activityCount.textContent=entries.length?visible+' of '+entries.length+' recent outcomes':'';noMatches.hidden=!entries.length||visible>0;}
      const watcher=root.querySelector('.watch-card');if(watcher)activity.append(watcher);const cloudNote=oldBody.querySelector(':scope > p');if(cloudNote){cloudNote.classList.add('screen-note');activity.append(cloudNote);}
      const runView=view('run','A live task has its own space. Green is confirmed, red is held, and amber needs verification. Every outcome comes from evidence.');runView.dataset.state='idle';runView.querySelector('.screen-heading').classList.add('run-heading');const signal=element('span','Waiting for a task','run-signal');signal.id='run-signal';runView.querySelector('.screen-heading').append(signal);
      source.classList.add('run-source');runView.append(source,root.querySelector('.assurance-board'),$('result'));
      const key=element('div',null,'outcome-key');key.setAttribute('aria-label','Outcome colour key');[['pass','Confirmed'],['held','Held · no action'],['review','Needs verification'],['live','Working']].forEach(([kind,label])=>key.append(element('span',label,kind)));runView.querySelector('.screen-heading').append(key);
      const actions=element('div',null,'run-actions');for(const [route,label] of [['home','New task'],['activity','View my activity']]){const b=element('button',label,'planner');b.type='button';b.dataset.screenLink=route;actions.append(b);}runView.append(actions,element('p','Never repeat an uncertain payment blindly. Check the recorded outcome first.','screen-note'));
      const outcomeSummary=element('section',null,'outcome-summary');outcomeSummary.setAttribute('role','status');outcomeSummary.setAttribute('aria-live','polite');outcomeSummary.setAttribute('aria-atomic','true');runView.insertBefore(outcomeSummary,source);
      const reasonCopy={RECIPIENT_MISMATCH:'The recipient differs from the enrolled provider.',AMOUNT_MISMATCH:'The requested amount differs from the provider bill.',UNUSUAL_BILL_INCREASE:'This bill rose beyond the increase you chose to review. Confirm the amount with the biller through a known channel.',EMBEDDED_INSTRUCTION:'The request tries to influence the safety checks.',RECURRING_REQUEST:'A recurring obligation is outside this one-time task.',ABOVE_AUTOMATIC_LIMIT:'This bill exceeds your automatic limit.',PROTECTED_BALANCE:'Paying would use your protected reserve.',DOCUMENT_EVIDENCE_INCOMPLETE:'The document does not provide all required source evidence.'};
      function summarize(title,copy,next){outcomeSummary.replaceChildren(element('h2',title),element('p',copy),element('small',next));}
      const originalSignalResult=showLiveResult;showLiveResult=function(data){originalSignalResult(data);const reasons=(data.reason||[]).map(r=>reasonCopy[r]||nice(r)).join(' ');if(data.state==='READY'){state('attention','Needs approval · no payment yet');summarize('Checked. Waiting for your decision.',reasons||'The bill matches the enrolled provider.','Review the details below before approving this artificial-money task.');}else if(data.state==='ATTENTION'){state('held','Stopped · no payment submitted');summarize('Friday stopped this request.',reasons||'The request could not be linked to an enrolled provider record.','Verify with the provider or correct the original request. Do not repeat an uncertain payment.');}else{summarize('Task result recorded.',data.message||'Check the recorded evidence below.','Your receipt and exact execution details are below.');}};
      const recordedInputResult=showLiveResult;showLiveResult=function(data){recordedInputResult(data);if(data.state==='ATTENTION'&&!data.bill_review){state('attention','Input understood · payment not verified');summarize('Your input is recorded, not a failed payment.',data.message||'Friday extracted the available facts.','Open My money → What Friday understood from your inputs to review them. No provider enrollment is needed for understanding; payment remains unavailable without trusted evidence.');}};
      const originalSelect=selectScenario;selectScenario=function(id){originalSelect(id);$('demo-description').textContent=catalogue.find(x=>x.id===id)?.description||'Choose a scenario.';$('scenario-copy').textContent='What can I take off your mind? Choose a task. I’ll handle the steps within your rules.';if(active==='home')setCore('READY','What should I handle?');};
      function show(name,push=true){if(!views[name])name='home';active=name;Object.entries(views).forEach(([key,v])=>v.hidden=key!==name);
        document.querySelectorAll('.friday-nav [data-screen-link]').forEach(b=>b.setAttribute('aria-current',b.dataset.screenLink===name?'page':'false'));document.title='Financial Friday · '+titles[name];
        if(name==='home'){if(!busy)setCore('READY','What should I handle?');refreshBriefing();refreshHouseholdBills();}if(push)history.pushState(null,'','#'+name);$('route-announcement').textContent=titles[name];window.scrollTo({top:0,behavior:'auto'});const h=views[name].querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}if(name==='activity')refreshActivity();if(name==='money')refreshMoney();}
      function state(kind,text){runView.dataset.state=kind;signal.textContent=text;runView.setAttribute('aria-busy',String(kind==='working'));}
      const evidenceDetails=$('result').querySelector('.mission-details');evidenceDetails.insertBefore($('briefing'),evidenceDetails.querySelector('summary').nextSibling);$('verdict').hidden=true;$('verdict').style.display='none';
      const completedStatuses=['COMPLETED_SYNTHETIC','ALREADY_COMPLETED','RECONCILED_COMPLETED'];
      const originalRender=render;render=function(r){originalRender(r);loadedRun=r.run_id;if(source.textContent.startsWith('Loading'))source.textContent='Recorded outcome loaded. Viewing this receipt does not submit another payment.';show('run',false);state(completedStatuses.includes(r.status)?'complete':r.status==='HELD'?'held':'attention',r.status==='HELD'?'Held · no new payment':r.status==='ALREADY_COMPLETED'?'Already handled · no repeat':r.status==='RECONCILED_COMPLETED'?'Recovered · no retry':r.status==='COMPLETED_SYNTHETIC'?'Completed · receipt recorded':'Attention · outcome not confirmed');summarize(r.status==='ALREADY_COMPLETED'?'Already handled. No repeat payment.':r.status==='COMPLETED_SYNTHETIC'?'Done. Your receipt is recorded.':r.status==='RECONCILED_COMPLETED'?'Previous outcome recovered. No blind retry.':r.status==='HELD'?'Stopped before a new payment.':'The outcome needs verification.',r.outcome?.message||'The status above is supported by the recorded run, not an animation.',completedStatuses.includes(r.status)?'You can reopen this receipt from Activity without submitting another payment.':'Read the evidence below before taking any further action.');};
      async function execute(fn,label){if(busy){toast('Friday is already handling a task. Check its outcome before starting another.');show('run',false);return;}
        busy=true;show('run');loadedRun=null;summarize('Friday is handling the checks.',label,'No result is assumed until the service returns verified evidence.');source.textContent=label;state('working','Working · awaiting verified result');
        try{await fn();}finally{busy=false;if(runView.dataset.state==='working'){state('attention','Outcome needs verification');summarize('Friday could not confirm the outcome.','No success is assumed when a service or connection fails.','Check Activity and the evidence below before retrying any financial task.');}}}
      const oldCheck=checkLive;checkLive=()=>{if(!$('live-input').value.trim()){toast('Add a bill request first.');$('live-input').focus();return Promise.resolve();}return execute(oldCheck,'Understanding your bill request…');};
      const oldDocument=checkDocument;checkDocument=()=>{if(!$('document-input').files.length){toast('Choose a bill image or PDF first.');$('document-input').focus();return Promise.resolve();}return execute(oldDocument,'Reading your document…');};
      const oldRun=run;run=()=>execute(oldRun,'Running a controlled safety scenario…');
      const originalVoice=startVoice;startVoice=function(){show('bill');originalVoice();};
      command.addEventListener('submit',e=>{e.preventDefault();const value=$('home-command').value.trim();show('bill');if(value){$('live-input').value=value;checkLive();}else $('live-input').focus();});
      async function refreshActivity(){list.replaceChildren(element('p','Loading recorded outcomes…','activity-empty'));activityCount.textContent='';noMatches.hidden=true;refresh.disabled=true;
        try{const data=await jsonRequest('/api/friday/today');list.replaceChildren();const runs=data.recent_runs||[];if(!runs.length)list.append(element('p','Nothing handled yet. Start with a bill or the safety lab.','activity-empty'));
          runs.forEach(r=>{if(!/^[A-Za-z0-9_-]{1,100}$/.test(r.run_id))return;const b=element('button',null,'activity-entry');b.type='button';b.dataset.runId=r.run_id;b.dataset.outcome=completedStatuses.includes(r.status)?'good':r.status==='HELD'?'held':'review';const copy=element('div');copy.append(element('b',nice(String(r.case_id||'Recorded task').replaceAll('-','_'))),element('small',r.run_id));const status=element('span',nice(r.status),'status '+b.dataset.outcome);b.append(copy,status);list.append(b);});filterActivity();
        }catch(e){list.replaceChildren(element('p','Activity could not be loaded. No payment was submitted. Try refreshing this read-only view.','activity-empty'));}finally{refresh.disabled=false;}}
      async function openRun(id){if(busy){toast('Wait for the current task to finish before reopening another run.');return;}show('run',false);$('result').classList.remove('visible');$('briefing').classList.remove('visible');source.textContent='Loading the recorded outcome. No payment is being submitted.';resetStages();state('working','Loading saved evidence');summarize('Opening your recorded receipt.','This is a read-only check, not another payment.','Waiting for the saved evidence.');
        try{render(await jsonRequest('/api/friday/runs/'+encodeURIComponent(id)));}catch(e){state('attention','Outcome unavailable');source.textContent='This recorded run could not be loaded. No payment was submitted. Check activity before retrying any financial task.';summarize('The saved evidence could not be loaded.','No payment was submitted by opening this page.','Return to Activity and refresh before retrying a financial task.');}}
      document.addEventListener('click',e=>{const target=e.target.closest('[data-screen-link],[data-run-id]');if(!target)return;if(target.dataset.runId){history.pushState(null,'','#run='+encodeURIComponent(target.dataset.runId));openRun(target.dataset.runId);}else show(target.dataset.screenLink);});refresh.addEventListener('click',refreshActivity);
      document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.ctrlKey||e.metaKey||e.altKey||guide.open||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='/'){e.preventDefault();show('home');$('home-command').focus();}else if(e.key==='?'){e.preventDefault();openGuide();}});
      function route(load=true){if(location.hash.startsWith('#run=')){show('run',false);if(load)openRun(decodeURIComponent(location.hash.slice(5)));else{source.textContent='Loading your recorded run…';state('working','Loading saved evidence');}}else show(location.hash.slice(1)||'home',false);}
      window.addEventListener('popstate',()=>route());window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#run=')&&loadedRun===decodeURIComponent(location.hash.slice(5)))return;route();});route(false);
      return {show,openRun};
    })();
"""


def enhance_friday_html(html: str) -> str:
    """Retain existing element IDs and API handlers while separating their views."""
    from .friday_simple import SIMPLE_CSS, SIMPLE_JS
    compact_js = EXPERIENCE_JS.replace("route(false);", SIMPLE_JS + "route(false);", 1)
    return (html.replace("</head>", EXPERIENCE_CSS + SIMPLE_CSS + "</head>", 1)
            .replace('<main class="shell layout">', EXPERIENCE_NAV + '<main class="shell layout">', 1)
            .replace("    let watching=false;", compact_js + "\n    let watching=false;", 1))
